#set page(width: 210mm, height: 297mm, margin: 0.5cm)
#set text(font: ("STIX", "STIX Two Text"))

= acute

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$acute(A)$], [Á], [$acute(a)$], [á],
      [$acute(B)$], [B́], [$acute(b)$], [b́],
      [$acute(C)$], [Ć], [$acute(c)$], [ć],
      [$acute(D)$], [D́], [$acute(d)$], [d́],
      [$acute(E)$], [É], [$acute(e)$], [é],
      [$acute(F)$], [F́], [$acute(f)$], [f́],
      [$acute(G)$], [Ǵ], [$acute(g)$], [ǵ],
      [$acute(H)$], [H́], [$acute(h)$], [h́],
      [$acute(I)$], [Í], [$acute(i)$], [í],
      [$acute(J)$], [J́], [$acute(j)$], [j́],
      [$acute(K)$], [Ḱ], [$acute(k)$], [ḱ],
      [$acute(L)$], [Ĺ], [$acute(l)$], [ĺ],
      [$acute(M)$], [Ḿ], [$acute(m)$], [ḿ],
      [$acute(N)$], [Ń], [$acute(n)$], [ń],
      [$acute(O)$], [Ó], [$acute(o)$], [ó],
      [$acute(P)$], [Ṕ], [$acute(p)$], [ṕ],
      [$acute(Q)$], [Q́], [$acute(q)$], [q́],
      [$acute(R)$], [Ŕ], [$acute(r)$], [ŕ],
      [$acute(S)$], [Ś], [$acute(s)$], [ś],
      [$acute(T)$], [T́], [$acute(t)$], [t́],
      [$acute(U)$], [Ú], [$acute(u)$], [ú],
      [$acute(V)$], [V́], [$acute(v)$], [v́],
      [$acute(W)$], [Ẃ], [$acute(w)$], [ẃ],
      [$acute(X)$], [X́], [$acute(x)$], [x́],
      [$acute(Y)$], [Ý], [$acute(y)$], [ý],
      [$acute(Z)$], [Ź], [$acute(z)$], [ź],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$acute(Alpha)$], [Ά], [$acute(alpha)$], [ά],
      [$acute(Beta)$], [Β́], [$acute(beta)$], [β́],
      [--], [--], [$acute(beta.alt)$], [ϐ́],
      [$acute(Chi)$], [Χ́], [$acute(chi)$], [χ́],
      [$acute(Delta)$], [Δ́], [$acute(delta)$], [δ́],
      [$acute(Digamma)$], [Ϝ́], [$acute(digamma)$], [ϝ́],
      [$acute(Epsilon)$], [Έ], [$acute(epsilon)$], [έ],
      [--], [--], [$acute(epsilon.alt)$], [ϵ́],
      [--], [--], [$acute(epsilon.alt.rev)$], [϶́],
      [--], [--], [$acute(epsilon.rev)$], [϶́],
      [--], [--], [$acute(epsilon.rev.alt)$], [϶́],
      [$acute(Eta)$], [Ή], [$acute(eta)$], [ή],
      [$acute(Gamma)$], [Γ́], [$acute(gamma)$], [γ́],
      [$acute(Iota)$], [Ί], [$acute(iota)$], [ί],
      [--], [--], [$acute(iota.inv)$], [℩́],
      [$acute(Kappa)$], [Κ́], [$acute(kappa)$], [κ́],
      [--], [--], [$acute(kappa.alt)$], [ϰ́],
      [$acute(Lambda)$], [Λ́], [$acute(lambda)$], [λ́],
      [$acute(Mu)$], [Μ́], [$acute(mu)$], [μ́],
      [$acute(Nu)$], [Ν́], [$acute(nu)$], [ν́],
      [$acute(Omega)$], [Ώ], [$acute(omega)$], [ώ],
      [--], [--], [$acute(Omega.inv)$], [℧́],
      [$acute(Omicron)$], [Ό], [$acute(omicron)$], [ό],
      [$acute(Phi)$], [Φ́], [$acute(phi)$], [φ́],
      [--], [--], [$acute(phi.alt)$], [ϕ́],
      [$acute(Pi)$], [Π́], [$acute(pi)$], [π́],
      [--], [--], [$acute(pi.alt)$], [ϖ́],
      [$acute(Psi)$], [Ψ́], [$acute(psi)$], [ψ́],
      [$acute(Rho)$], [Ρ́], [$acute(rho)$], [ρ́],
      [--], [--], [$acute(rho.alt)$], [ϱ́],
      [$acute(Sigma)$], [Σ́], [$acute(sigma)$], [σ́],
      [--], [--], [$acute(sigma.alt)$], [ς́],
      [$acute(Tau)$], [Τ́], [$acute(tau)$], [τ́],
      [$acute(Theta)$], [Θ́], [$acute(theta)$], [θ́],
      [--], [--], [$acute(theta.alt)$], [ϑ́],
      [--], [--], [$acute(Theta.alt)$], [ϴ́],
      [$acute(Upsilon)$], [Ύ], [$acute(upsilon)$], [ύ],
      [$acute(Xi)$], [Ξ́], [$acute(xi)$], [ξ́],
      [$acute(Zeta)$], [Ζ́], [$acute(zeta)$], [ζ́],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$acute(0)$], [0́],
      [$acute(1)$], [1́],
      [$acute(2)$], [2́],
      [$acute(3)$], [3́],
      [$acute(4)$], [4́],
      [$acute(5)$], [5́],
      [$acute(6)$], [6́],
      [$acute(7)$], [7́],
      [$acute(8)$], [8́],
      [$acute(9)$], [9́],
    )
  ],
)

#pagebreak()

= acute.double

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$acute.double(A)$], [A̋], [$acute.double(a)$], [a̋],
      [$acute.double(B)$], [B̋], [$acute.double(b)$], [b̋],
      [$acute.double(C)$], [C̋], [$acute.double(c)$], [c̋],
      [$acute.double(D)$], [D̋], [$acute.double(d)$], [d̋],
      [$acute.double(E)$], [E̋], [$acute.double(e)$], [e̋],
      [$acute.double(F)$], [F̋], [$acute.double(f)$], [f̋],
      [$acute.double(G)$], [G̋], [$acute.double(g)$], [g̋],
      [$acute.double(H)$], [H̋], [$acute.double(h)$], [h̋],
      [$acute.double(I)$], [I̋], [$acute.double(i)$], [i̋],
      [$acute.double(J)$], [J̋], [$acute.double(j)$], [j̋],
      [$acute.double(K)$], [K̋], [$acute.double(k)$], [k̋],
      [$acute.double(L)$], [L̋], [$acute.double(l)$], [l̋],
      [$acute.double(M)$], [M̋], [$acute.double(m)$], [m̋],
      [$acute.double(N)$], [N̋], [$acute.double(n)$], [n̋],
      [$acute.double(O)$], [Ő], [$acute.double(o)$], [ő],
      [$acute.double(P)$], [P̋], [$acute.double(p)$], [p̋],
      [$acute.double(Q)$], [Q̋], [$acute.double(q)$], [q̋],
      [$acute.double(R)$], [R̋], [$acute.double(r)$], [r̋],
      [$acute.double(S)$], [S̋], [$acute.double(s)$], [s̋],
      [$acute.double(T)$], [T̋], [$acute.double(t)$], [t̋],
      [$acute.double(U)$], [Ű], [$acute.double(u)$], [ű],
      [$acute.double(V)$], [V̋], [$acute.double(v)$], [v̋],
      [$acute.double(W)$], [W̋], [$acute.double(w)$], [w̋],
      [$acute.double(X)$], [X̋], [$acute.double(x)$], [x̋],
      [$acute.double(Y)$], [Y̋], [$acute.double(y)$], [y̋],
      [$acute.double(Z)$], [Z̋], [$acute.double(z)$], [z̋],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$acute.double(Alpha)$], [Α̋], [$acute.double(alpha)$], [α̋],
      [$acute.double(Beta)$], [Β̋], [$acute.double(beta)$], [β̋],
      [--], [--], [$acute.double(beta.alt)$], [ϐ̋],
      [$acute.double(Chi)$], [Χ̋], [$acute.double(chi)$], [χ̋],
      [$acute.double(Delta)$], [Δ̋], [$acute.double(delta)$], [δ̋],
      [$acute.double(Digamma)$], [Ϝ̋], [$acute.double(digamma)$], [ϝ̋],
      [$acute.double(Epsilon)$], [Ε̋], [$acute.double(epsilon)$], [ε̋],
      [--], [--], [$acute.double(epsilon.alt)$], [ϵ̋],
      [--], [--], [$acute.double(epsilon.alt.rev)$], [϶̋],
      [--], [--], [$acute.double(epsilon.rev)$], [϶̋],
      [--], [--], [$acute.double(epsilon.rev.alt)$], [϶̋],
      [$acute.double(Eta)$], [Η̋], [$acute.double(eta)$], [η̋],
      [$acute.double(Gamma)$], [Γ̋], [$acute.double(gamma)$], [γ̋],
      [$acute.double(Iota)$], [Ι̋], [$acute.double(iota)$], [ι̋],
      [--], [--], [$acute.double(iota.inv)$], [℩̋],
      [$acute.double(Kappa)$], [Κ̋], [$acute.double(kappa)$], [κ̋],
      [--], [--], [$acute.double(kappa.alt)$], [ϰ̋],
      [$acute.double(Lambda)$], [Λ̋], [$acute.double(lambda)$], [λ̋],
      [$acute.double(Mu)$], [Μ̋], [$acute.double(mu)$], [μ̋],
      [$acute.double(Nu)$], [Ν̋], [$acute.double(nu)$], [ν̋],
      [$acute.double(Omega)$], [Ω̋], [$acute.double(omega)$], [ω̋],
      [--], [--], [$acute.double(Omega.inv)$], [℧̋],
      [$acute.double(Omicron)$], [Ο̋], [$acute.double(omicron)$], [ο̋],
      [$acute.double(Phi)$], [Φ̋], [$acute.double(phi)$], [φ̋],
      [--], [--], [$acute.double(phi.alt)$], [ϕ̋],
      [$acute.double(Pi)$], [Π̋], [$acute.double(pi)$], [π̋],
      [--], [--], [$acute.double(pi.alt)$], [ϖ̋],
      [$acute.double(Psi)$], [Ψ̋], [$acute.double(psi)$], [ψ̋],
      [$acute.double(Rho)$], [Ρ̋], [$acute.double(rho)$], [ρ̋],
      [--], [--], [$acute.double(rho.alt)$], [ϱ̋],
      [$acute.double(Sigma)$], [Σ̋], [$acute.double(sigma)$], [σ̋],
      [--], [--], [$acute.double(sigma.alt)$], [ς̋],
      [$acute.double(Tau)$], [Τ̋], [$acute.double(tau)$], [τ̋],
      [$acute.double(Theta)$], [Θ̋], [$acute.double(theta)$], [θ̋],
      [--], [--], [$acute.double(theta.alt)$], [ϑ̋],
      [--], [--], [$acute.double(Theta.alt)$], [ϴ̋],
      [$acute.double(Upsilon)$], [Υ̋], [$acute.double(upsilon)$], [υ̋],
      [$acute.double(Xi)$], [Ξ̋], [$acute.double(xi)$], [ξ̋],
      [$acute.double(Zeta)$], [Ζ̋], [$acute.double(zeta)$], [ζ̋],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$acute.double(0)$], [0̋],
      [$acute.double(1)$], [1̋],
      [$acute.double(2)$], [2̋],
      [$acute.double(3)$], [3̋],
      [$acute.double(4)$], [4̋],
      [$acute.double(5)$], [5̋],
      [$acute.double(6)$], [6̋],
      [$acute.double(7)$], [7̋],
      [$acute.double(8)$], [8̋],
      [$acute.double(9)$], [9̋],
    )
  ],
)

#pagebreak()

= arrow

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$arrow(A)$], [A⃗], [$arrow(a)$], [a⃗],
      [$arrow(B)$], [B⃗], [$arrow(b)$], [b⃗],
      [$arrow(C)$], [C⃗], [$arrow(c)$], [c⃗],
      [$arrow(D)$], [D⃗], [$arrow(d)$], [d⃗],
      [$arrow(E)$], [E⃗], [$arrow(e)$], [e⃗],
      [$arrow(F)$], [F⃗], [$arrow(f)$], [f⃗],
      [$arrow(G)$], [G⃗], [$arrow(g)$], [g⃗],
      [$arrow(H)$], [H⃗], [$arrow(h)$], [h⃗],
      [$arrow(I)$], [I⃗], [$arrow(i)$], [i⃗],
      [$arrow(J)$], [J⃗], [$arrow(j)$], [j⃗],
      [$arrow(K)$], [K⃗], [$arrow(k)$], [k⃗],
      [$arrow(L)$], [L⃗], [$arrow(l)$], [l⃗],
      [$arrow(M)$], [M⃗], [$arrow(m)$], [m⃗],
      [$arrow(N)$], [N⃗], [$arrow(n)$], [n⃗],
      [$arrow(O)$], [O⃗], [$arrow(o)$], [o⃗],
      [$arrow(P)$], [P⃗], [$arrow(p)$], [p⃗],
      [$arrow(Q)$], [Q⃗], [$arrow(q)$], [q⃗],
      [$arrow(R)$], [R⃗], [$arrow(r)$], [r⃗],
      [$arrow(S)$], [S⃗], [$arrow(s)$], [s⃗],
      [$arrow(T)$], [T⃗], [$arrow(t)$], [t⃗],
      [$arrow(U)$], [U⃗], [$arrow(u)$], [u⃗],
      [$arrow(V)$], [V⃗], [$arrow(v)$], [v⃗],
      [$arrow(W)$], [W⃗], [$arrow(w)$], [w⃗],
      [$arrow(X)$], [X⃗], [$arrow(x)$], [x⃗],
      [$arrow(Y)$], [Y⃗], [$arrow(y)$], [y⃗],
      [$arrow(Z)$], [Z⃗], [$arrow(z)$], [z⃗],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$arrow(Alpha)$], [Α⃗], [$arrow(alpha)$], [α⃗],
      [$arrow(Beta)$], [Β⃗], [$arrow(beta)$], [β⃗],
      [--], [--], [$arrow(beta.alt)$], [ϐ⃗],
      [$arrow(Chi)$], [Χ⃗], [$arrow(chi)$], [χ⃗],
      [$arrow(Delta)$], [Δ⃗], [$arrow(delta)$], [δ⃗],
      [$arrow(Digamma)$], [Ϝ⃗], [$arrow(digamma)$], [ϝ⃗],
      [$arrow(Epsilon)$], [Ε⃗], [$arrow(epsilon)$], [ε⃗],
      [--], [--], [$arrow(epsilon.alt)$], [ϵ⃗],
      [--], [--], [$arrow(epsilon.alt.rev)$], [϶⃗],
      [--], [--], [$arrow(epsilon.rev)$], [϶⃗],
      [--], [--], [$arrow(epsilon.rev.alt)$], [϶⃗],
      [$arrow(Eta)$], [Η⃗], [$arrow(eta)$], [η⃗],
      [$arrow(Gamma)$], [Γ⃗], [$arrow(gamma)$], [γ⃗],
      [$arrow(Iota)$], [Ι⃗], [$arrow(iota)$], [ι⃗],
      [--], [--], [$arrow(iota.inv)$], [℩⃗],
      [$arrow(Kappa)$], [Κ⃗], [$arrow(kappa)$], [κ⃗],
      [--], [--], [$arrow(kappa.alt)$], [ϰ⃗],
      [$arrow(Lambda)$], [Λ⃗], [$arrow(lambda)$], [λ⃗],
      [$arrow(Mu)$], [Μ⃗], [$arrow(mu)$], [μ⃗],
      [$arrow(Nu)$], [Ν⃗], [$arrow(nu)$], [ν⃗],
      [$arrow(Omega)$], [Ω⃗], [$arrow(omega)$], [ω⃗],
      [--], [--], [$arrow(Omega.inv)$], [℧⃗],
      [$arrow(Omicron)$], [Ο⃗], [$arrow(omicron)$], [ο⃗],
      [$arrow(Phi)$], [Φ⃗], [$arrow(phi)$], [φ⃗],
      [--], [--], [$arrow(phi.alt)$], [ϕ⃗],
      [$arrow(Pi)$], [Π⃗], [$arrow(pi)$], [π⃗],
      [--], [--], [$arrow(pi.alt)$], [ϖ⃗],
      [$arrow(Psi)$], [Ψ⃗], [$arrow(psi)$], [ψ⃗],
      [$arrow(Rho)$], [Ρ⃗], [$arrow(rho)$], [ρ⃗],
      [--], [--], [$arrow(rho.alt)$], [ϱ⃗],
      [$arrow(Sigma)$], [Σ⃗], [$arrow(sigma)$], [σ⃗],
      [--], [--], [$arrow(sigma.alt)$], [ς⃗],
      [$arrow(Tau)$], [Τ⃗], [$arrow(tau)$], [τ⃗],
      [$arrow(Theta)$], [Θ⃗], [$arrow(theta)$], [θ⃗],
      [--], [--], [$arrow(theta.alt)$], [ϑ⃗],
      [--], [--], [$arrow(Theta.alt)$], [ϴ⃗],
      [$arrow(Upsilon)$], [Υ⃗], [$arrow(upsilon)$], [υ⃗],
      [$arrow(Xi)$], [Ξ⃗], [$arrow(xi)$], [ξ⃗],
      [$arrow(Zeta)$], [Ζ⃗], [$arrow(zeta)$], [ζ⃗],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$arrow(0)$], [0⃗],
      [$arrow(1)$], [1⃗],
      [$arrow(2)$], [2⃗],
      [$arrow(3)$], [3⃗],
      [$arrow(4)$], [4⃗],
      [$arrow(5)$], [5⃗],
      [$arrow(6)$], [6⃗],
      [$arrow(7)$], [7⃗],
      [$arrow(8)$], [8⃗],
      [$arrow(9)$], [9⃗],
    )
  ],
)

#pagebreak()

= arrow.l

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$arrow.l(A)$], [A⃖], [$arrow.l(a)$], [a⃖],
      [$arrow.l(B)$], [B⃖], [$arrow.l(b)$], [b⃖],
      [$arrow.l(C)$], [C⃖], [$arrow.l(c)$], [c⃖],
      [$arrow.l(D)$], [D⃖], [$arrow.l(d)$], [d⃖],
      [$arrow.l(E)$], [E⃖], [$arrow.l(e)$], [e⃖],
      [$arrow.l(F)$], [F⃖], [$arrow.l(f)$], [f⃖],
      [$arrow.l(G)$], [G⃖], [$arrow.l(g)$], [g⃖],
      [$arrow.l(H)$], [H⃖], [$arrow.l(h)$], [h⃖],
      [$arrow.l(I)$], [I⃖], [$arrow.l(i)$], [i⃖],
      [$arrow.l(J)$], [J⃖], [$arrow.l(j)$], [j⃖],
      [$arrow.l(K)$], [K⃖], [$arrow.l(k)$], [k⃖],
      [$arrow.l(L)$], [L⃖], [$arrow.l(l)$], [l⃖],
      [$arrow.l(M)$], [M⃖], [$arrow.l(m)$], [m⃖],
      [$arrow.l(N)$], [N⃖], [$arrow.l(n)$], [n⃖],
      [$arrow.l(O)$], [O⃖], [$arrow.l(o)$], [o⃖],
      [$arrow.l(P)$], [P⃖], [$arrow.l(p)$], [p⃖],
      [$arrow.l(Q)$], [Q⃖], [$arrow.l(q)$], [q⃖],
      [$arrow.l(R)$], [R⃖], [$arrow.l(r)$], [r⃖],
      [$arrow.l(S)$], [S⃖], [$arrow.l(s)$], [s⃖],
      [$arrow.l(T)$], [T⃖], [$arrow.l(t)$], [t⃖],
      [$arrow.l(U)$], [U⃖], [$arrow.l(u)$], [u⃖],
      [$arrow.l(V)$], [V⃖], [$arrow.l(v)$], [v⃖],
      [$arrow.l(W)$], [W⃖], [$arrow.l(w)$], [w⃖],
      [$arrow.l(X)$], [X⃖], [$arrow.l(x)$], [x⃖],
      [$arrow.l(Y)$], [Y⃖], [$arrow.l(y)$], [y⃖],
      [$arrow.l(Z)$], [Z⃖], [$arrow.l(z)$], [z⃖],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$arrow.l(Alpha)$], [Α⃖], [$arrow.l(alpha)$], [α⃖],
      [$arrow.l(Beta)$], [Β⃖], [$arrow.l(beta)$], [β⃖],
      [--], [--], [$arrow.l(beta.alt)$], [ϐ⃖],
      [$arrow.l(Chi)$], [Χ⃖], [$arrow.l(chi)$], [χ⃖],
      [$arrow.l(Delta)$], [Δ⃖], [$arrow.l(delta)$], [δ⃖],
      [$arrow.l(Digamma)$], [Ϝ⃖], [$arrow.l(digamma)$], [ϝ⃖],
      [$arrow.l(Epsilon)$], [Ε⃖], [$arrow.l(epsilon)$], [ε⃖],
      [--], [--], [$arrow.l(epsilon.alt)$], [ϵ⃖],
      [--], [--], [$arrow.l(epsilon.alt.rev)$], [϶⃖],
      [--], [--], [$arrow.l(epsilon.rev)$], [϶⃖],
      [--], [--], [$arrow.l(epsilon.rev.alt)$], [϶⃖],
      [$arrow.l(Eta)$], [Η⃖], [$arrow.l(eta)$], [η⃖],
      [$arrow.l(Gamma)$], [Γ⃖], [$arrow.l(gamma)$], [γ⃖],
      [$arrow.l(Iota)$], [Ι⃖], [$arrow.l(iota)$], [ι⃖],
      [--], [--], [$arrow.l(iota.inv)$], [℩⃖],
      [$arrow.l(Kappa)$], [Κ⃖], [$arrow.l(kappa)$], [κ⃖],
      [--], [--], [$arrow.l(kappa.alt)$], [ϰ⃖],
      [$arrow.l(Lambda)$], [Λ⃖], [$arrow.l(lambda)$], [λ⃖],
      [$arrow.l(Mu)$], [Μ⃖], [$arrow.l(mu)$], [μ⃖],
      [$arrow.l(Nu)$], [Ν⃖], [$arrow.l(nu)$], [ν⃖],
      [$arrow.l(Omega)$], [Ω⃖], [$arrow.l(omega)$], [ω⃖],
      [--], [--], [$arrow.l(Omega.inv)$], [℧⃖],
      [$arrow.l(Omicron)$], [Ο⃖], [$arrow.l(omicron)$], [ο⃖],
      [$arrow.l(Phi)$], [Φ⃖], [$arrow.l(phi)$], [φ⃖],
      [--], [--], [$arrow.l(phi.alt)$], [ϕ⃖],
      [$arrow.l(Pi)$], [Π⃖], [$arrow.l(pi)$], [π⃖],
      [--], [--], [$arrow.l(pi.alt)$], [ϖ⃖],
      [$arrow.l(Psi)$], [Ψ⃖], [$arrow.l(psi)$], [ψ⃖],
      [$arrow.l(Rho)$], [Ρ⃖], [$arrow.l(rho)$], [ρ⃖],
      [--], [--], [$arrow.l(rho.alt)$], [ϱ⃖],
      [$arrow.l(Sigma)$], [Σ⃖], [$arrow.l(sigma)$], [σ⃖],
      [--], [--], [$arrow.l(sigma.alt)$], [ς⃖],
      [$arrow.l(Tau)$], [Τ⃖], [$arrow.l(tau)$], [τ⃖],
      [$arrow.l(Theta)$], [Θ⃖], [$arrow.l(theta)$], [θ⃖],
      [--], [--], [$arrow.l(theta.alt)$], [ϑ⃖],
      [--], [--], [$arrow.l(Theta.alt)$], [ϴ⃖],
      [$arrow.l(Upsilon)$], [Υ⃖], [$arrow.l(upsilon)$], [υ⃖],
      [$arrow.l(Xi)$], [Ξ⃖], [$arrow.l(xi)$], [ξ⃖],
      [$arrow.l(Zeta)$], [Ζ⃖], [$arrow.l(zeta)$], [ζ⃖],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$arrow.l(0)$], [0⃖],
      [$arrow.l(1)$], [1⃖],
      [$arrow.l(2)$], [2⃖],
      [$arrow.l(3)$], [3⃖],
      [$arrow.l(4)$], [4⃖],
      [$arrow.l(5)$], [5⃖],
      [$arrow.l(6)$], [6⃖],
      [$arrow.l(7)$], [7⃖],
      [$arrow.l(8)$], [8⃖],
      [$arrow.l(9)$], [9⃖],
    )
  ],
)

#pagebreak()

= arrow.l.r

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$arrow.l.r(A)$], [A⃡], [$arrow.l.r(a)$], [a⃡],
      [$arrow.l.r(B)$], [B⃡], [$arrow.l.r(b)$], [b⃡],
      [$arrow.l.r(C)$], [C⃡], [$arrow.l.r(c)$], [c⃡],
      [$arrow.l.r(D)$], [D⃡], [$arrow.l.r(d)$], [d⃡],
      [$arrow.l.r(E)$], [E⃡], [$arrow.l.r(e)$], [e⃡],
      [$arrow.l.r(F)$], [F⃡], [$arrow.l.r(f)$], [f⃡],
      [$arrow.l.r(G)$], [G⃡], [$arrow.l.r(g)$], [g⃡],
      [$arrow.l.r(H)$], [H⃡], [$arrow.l.r(h)$], [h⃡],
      [$arrow.l.r(I)$], [I⃡], [$arrow.l.r(i)$], [i⃡],
      [$arrow.l.r(J)$], [J⃡], [$arrow.l.r(j)$], [j⃡],
      [$arrow.l.r(K)$], [K⃡], [$arrow.l.r(k)$], [k⃡],
      [$arrow.l.r(L)$], [L⃡], [$arrow.l.r(l)$], [l⃡],
      [$arrow.l.r(M)$], [M⃡], [$arrow.l.r(m)$], [m⃡],
      [$arrow.l.r(N)$], [N⃡], [$arrow.l.r(n)$], [n⃡],
      [$arrow.l.r(O)$], [O⃡], [$arrow.l.r(o)$], [o⃡],
      [$arrow.l.r(P)$], [P⃡], [$arrow.l.r(p)$], [p⃡],
      [$arrow.l.r(Q)$], [Q⃡], [$arrow.l.r(q)$], [q⃡],
      [$arrow.l.r(R)$], [R⃡], [$arrow.l.r(r)$], [r⃡],
      [$arrow.l.r(S)$], [S⃡], [$arrow.l.r(s)$], [s⃡],
      [$arrow.l.r(T)$], [T⃡], [$arrow.l.r(t)$], [t⃡],
      [$arrow.l.r(U)$], [U⃡], [$arrow.l.r(u)$], [u⃡],
      [$arrow.l.r(V)$], [V⃡], [$arrow.l.r(v)$], [v⃡],
      [$arrow.l.r(W)$], [W⃡], [$arrow.l.r(w)$], [w⃡],
      [$arrow.l.r(X)$], [X⃡], [$arrow.l.r(x)$], [x⃡],
      [$arrow.l.r(Y)$], [Y⃡], [$arrow.l.r(y)$], [y⃡],
      [$arrow.l.r(Z)$], [Z⃡], [$arrow.l.r(z)$], [z⃡],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$arrow.l.r(Alpha)$], [Α⃡], [$arrow.l.r(alpha)$], [α⃡],
      [$arrow.l.r(Beta)$], [Β⃡], [$arrow.l.r(beta)$], [β⃡],
      [--], [--], [$arrow.l.r(beta.alt)$], [ϐ⃡],
      [$arrow.l.r(Chi)$], [Χ⃡], [$arrow.l.r(chi)$], [χ⃡],
      [$arrow.l.r(Delta)$], [Δ⃡], [$arrow.l.r(delta)$], [δ⃡],
      [$arrow.l.r(Digamma)$], [Ϝ⃡], [$arrow.l.r(digamma)$], [ϝ⃡],
      [$arrow.l.r(Epsilon)$], [Ε⃡], [$arrow.l.r(epsilon)$], [ε⃡],
      [--], [--], [$arrow.l.r(epsilon.alt)$], [ϵ⃡],
      [--], [--], [$arrow.l.r(epsilon.alt.rev)$], [϶⃡],
      [--], [--], [$arrow.l.r(epsilon.rev)$], [϶⃡],
      [--], [--], [$arrow.l.r(epsilon.rev.alt)$], [϶⃡],
      [$arrow.l.r(Eta)$], [Η⃡], [$arrow.l.r(eta)$], [η⃡],
      [$arrow.l.r(Gamma)$], [Γ⃡], [$arrow.l.r(gamma)$], [γ⃡],
      [$arrow.l.r(Iota)$], [Ι⃡], [$arrow.l.r(iota)$], [ι⃡],
      [--], [--], [$arrow.l.r(iota.inv)$], [℩⃡],
      [$arrow.l.r(Kappa)$], [Κ⃡], [$arrow.l.r(kappa)$], [κ⃡],
      [--], [--], [$arrow.l.r(kappa.alt)$], [ϰ⃡],
      [$arrow.l.r(Lambda)$], [Λ⃡], [$arrow.l.r(lambda)$], [λ⃡],
      [$arrow.l.r(Mu)$], [Μ⃡], [$arrow.l.r(mu)$], [μ⃡],
      [$arrow.l.r(Nu)$], [Ν⃡], [$arrow.l.r(nu)$], [ν⃡],
      [$arrow.l.r(Omega)$], [Ω⃡], [$arrow.l.r(omega)$], [ω⃡],
      [--], [--], [$arrow.l.r(Omega.inv)$], [℧⃡],
      [$arrow.l.r(Omicron)$], [Ο⃡], [$arrow.l.r(omicron)$], [ο⃡],
      [$arrow.l.r(Phi)$], [Φ⃡], [$arrow.l.r(phi)$], [φ⃡],
      [--], [--], [$arrow.l.r(phi.alt)$], [ϕ⃡],
      [$arrow.l.r(Pi)$], [Π⃡], [$arrow.l.r(pi)$], [π⃡],
      [--], [--], [$arrow.l.r(pi.alt)$], [ϖ⃡],
      [$arrow.l.r(Psi)$], [Ψ⃡], [$arrow.l.r(psi)$], [ψ⃡],
      [$arrow.l.r(Rho)$], [Ρ⃡], [$arrow.l.r(rho)$], [ρ⃡],
      [--], [--], [$arrow.l.r(rho.alt)$], [ϱ⃡],
      [$arrow.l.r(Sigma)$], [Σ⃡], [$arrow.l.r(sigma)$], [σ⃡],
      [--], [--], [$arrow.l.r(sigma.alt)$], [ς⃡],
      [$arrow.l.r(Tau)$], [Τ⃡], [$arrow.l.r(tau)$], [τ⃡],
      [$arrow.l.r(Theta)$], [Θ⃡], [$arrow.l.r(theta)$], [θ⃡],
      [--], [--], [$arrow.l.r(theta.alt)$], [ϑ⃡],
      [--], [--], [$arrow.l.r(Theta.alt)$], [ϴ⃡],
      [$arrow.l.r(Upsilon)$], [Υ⃡], [$arrow.l.r(upsilon)$], [υ⃡],
      [$arrow.l.r(Xi)$], [Ξ⃡], [$arrow.l.r(xi)$], [ξ⃡],
      [$arrow.l.r(Zeta)$], [Ζ⃡], [$arrow.l.r(zeta)$], [ζ⃡],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$arrow.l.r(0)$], [0⃡],
      [$arrow.l.r(1)$], [1⃡],
      [$arrow.l.r(2)$], [2⃡],
      [$arrow.l.r(3)$], [3⃡],
      [$arrow.l.r(4)$], [4⃡],
      [$arrow.l.r(5)$], [5⃡],
      [$arrow.l.r(6)$], [6⃡],
      [$arrow.l.r(7)$], [7⃡],
      [$arrow.l.r(8)$], [8⃡],
      [$arrow.l.r(9)$], [9⃡],
    )
  ],
)

#pagebreak()

= breve

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$breve(A)$], [Ă], [$breve(a)$], [ă],
      [$breve(B)$], [B̆], [$breve(b)$], [b̆],
      [$breve(C)$], [C̆], [$breve(c)$], [c̆],
      [$breve(D)$], [D̆], [$breve(d)$], [d̆],
      [$breve(E)$], [Ĕ], [$breve(e)$], [ĕ],
      [$breve(F)$], [F̆], [$breve(f)$], [f̆],
      [$breve(G)$], [Ğ], [$breve(g)$], [ğ],
      [$breve(H)$], [H̆], [$breve(h)$], [h̆],
      [$breve(I)$], [Ĭ], [$breve(i)$], [ĭ],
      [$breve(J)$], [J̆], [$breve(j)$], [j̆],
      [$breve(K)$], [K̆], [$breve(k)$], [k̆],
      [$breve(L)$], [L̆], [$breve(l)$], [l̆],
      [$breve(M)$], [M̆], [$breve(m)$], [m̆],
      [$breve(N)$], [N̆], [$breve(n)$], [n̆],
      [$breve(O)$], [Ŏ], [$breve(o)$], [ŏ],
      [$breve(P)$], [P̆], [$breve(p)$], [p̆],
      [$breve(Q)$], [Q̆], [$breve(q)$], [q̆],
      [$breve(R)$], [R̆], [$breve(r)$], [r̆],
      [$breve(S)$], [S̆], [$breve(s)$], [s̆],
      [$breve(T)$], [T̆], [$breve(t)$], [t̆],
      [$breve(U)$], [Ŭ], [$breve(u)$], [ŭ],
      [$breve(V)$], [V̆], [$breve(v)$], [v̆],
      [$breve(W)$], [W̆], [$breve(w)$], [w̆],
      [$breve(X)$], [X̆], [$breve(x)$], [x̆],
      [$breve(Y)$], [Y̆], [$breve(y)$], [y̆],
      [$breve(Z)$], [Z̆], [$breve(z)$], [z̆],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$breve(Alpha)$], [Ᾰ], [$breve(alpha)$], [ᾰ],
      [$breve(Beta)$], [Β̆], [$breve(beta)$], [β̆],
      [--], [--], [$breve(beta.alt)$], [ϐ̆],
      [$breve(Chi)$], [Χ̆], [$breve(chi)$], [χ̆],
      [$breve(Delta)$], [Δ̆], [$breve(delta)$], [δ̆],
      [$breve(Digamma)$], [Ϝ̆], [$breve(digamma)$], [ϝ̆],
      [$breve(Epsilon)$], [Ε̆], [$breve(epsilon)$], [ε̆],
      [--], [--], [$breve(epsilon.alt)$], [ϵ̆],
      [--], [--], [$breve(epsilon.alt.rev)$], [϶̆],
      [--], [--], [$breve(epsilon.rev)$], [϶̆],
      [--], [--], [$breve(epsilon.rev.alt)$], [϶̆],
      [$breve(Eta)$], [Η̆], [$breve(eta)$], [η̆],
      [$breve(Gamma)$], [Γ̆], [$breve(gamma)$], [γ̆],
      [$breve(Iota)$], [Ῐ], [$breve(iota)$], [ῐ],
      [--], [--], [$breve(iota.inv)$], [℩̆],
      [$breve(Kappa)$], [Κ̆], [$breve(kappa)$], [κ̆],
      [--], [--], [$breve(kappa.alt)$], [ϰ̆],
      [$breve(Lambda)$], [Λ̆], [$breve(lambda)$], [λ̆],
      [$breve(Mu)$], [Μ̆], [$breve(mu)$], [μ̆],
      [$breve(Nu)$], [Ν̆], [$breve(nu)$], [ν̆],
      [$breve(Omega)$], [Ω̆], [$breve(omega)$], [ω̆],
      [--], [--], [$breve(Omega.inv)$], [℧̆],
      [$breve(Omicron)$], [Ο̆], [$breve(omicron)$], [ο̆],
      [$breve(Phi)$], [Φ̆], [$breve(phi)$], [φ̆],
      [--], [--], [$breve(phi.alt)$], [ϕ̆],
      [$breve(Pi)$], [Π̆], [$breve(pi)$], [π̆],
      [--], [--], [$breve(pi.alt)$], [ϖ̆],
      [$breve(Psi)$], [Ψ̆], [$breve(psi)$], [ψ̆],
      [$breve(Rho)$], [Ρ̆], [$breve(rho)$], [ρ̆],
      [--], [--], [$breve(rho.alt)$], [ϱ̆],
      [$breve(Sigma)$], [Σ̆], [$breve(sigma)$], [σ̆],
      [--], [--], [$breve(sigma.alt)$], [ς̆],
      [$breve(Tau)$], [Τ̆], [$breve(tau)$], [τ̆],
      [$breve(Theta)$], [Θ̆], [$breve(theta)$], [θ̆],
      [--], [--], [$breve(theta.alt)$], [ϑ̆],
      [--], [--], [$breve(Theta.alt)$], [ϴ̆],
      [$breve(Upsilon)$], [Ῠ], [$breve(upsilon)$], [ῠ],
      [$breve(Xi)$], [Ξ̆], [$breve(xi)$], [ξ̆],
      [$breve(Zeta)$], [Ζ̆], [$breve(zeta)$], [ζ̆],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$breve(0)$], [0̆],
      [$breve(1)$], [1̆],
      [$breve(2)$], [2̆],
      [$breve(3)$], [3̆],
      [$breve(4)$], [4̆],
      [$breve(5)$], [5̆],
      [$breve(6)$], [6̆],
      [$breve(7)$], [7̆],
      [$breve(8)$], [8̆],
      [$breve(9)$], [9̆],
    )
  ],
)

#pagebreak()

= caron

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$caron(A)$], [Ǎ], [$caron(a)$], [ǎ],
      [$caron(B)$], [B̌], [$caron(b)$], [b̌],
      [$caron(C)$], [Č], [$caron(c)$], [č],
      [$caron(D)$], [Ď], [$caron(d)$], [ď],
      [$caron(E)$], [Ě], [$caron(e)$], [ě],
      [$caron(F)$], [F̌], [$caron(f)$], [f̌],
      [$caron(G)$], [Ǧ], [$caron(g)$], [ǧ],
      [$caron(H)$], [Ȟ], [$caron(h)$], [ȟ],
      [$caron(I)$], [Ǐ], [$caron(i)$], [ǐ],
      [$caron(J)$], [J̌], [$caron(j)$], [ǰ],
      [$caron(K)$], [Ǩ], [$caron(k)$], [ǩ],
      [$caron(L)$], [Ľ], [$caron(l)$], [ľ],
      [$caron(M)$], [M̌], [$caron(m)$], [m̌],
      [$caron(N)$], [Ň], [$caron(n)$], [ň],
      [$caron(O)$], [Ǒ], [$caron(o)$], [ǒ],
      [$caron(P)$], [P̌], [$caron(p)$], [p̌],
      [$caron(Q)$], [Q̌], [$caron(q)$], [q̌],
      [$caron(R)$], [Ř], [$caron(r)$], [ř],
      [$caron(S)$], [Š], [$caron(s)$], [š],
      [$caron(T)$], [Ť], [$caron(t)$], [ť],
      [$caron(U)$], [Ǔ], [$caron(u)$], [ǔ],
      [$caron(V)$], [V̌], [$caron(v)$], [v̌],
      [$caron(W)$], [W̌], [$caron(w)$], [w̌],
      [$caron(X)$], [X̌], [$caron(x)$], [x̌],
      [$caron(Y)$], [Y̌], [$caron(y)$], [y̌],
      [$caron(Z)$], [Ž], [$caron(z)$], [ž],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$caron(Alpha)$], [Α̌], [$caron(alpha)$], [α̌],
      [$caron(Beta)$], [Β̌], [$caron(beta)$], [β̌],
      [--], [--], [$caron(beta.alt)$], [ϐ̌],
      [$caron(Chi)$], [Χ̌], [$caron(chi)$], [χ̌],
      [$caron(Delta)$], [Δ̌], [$caron(delta)$], [δ̌],
      [$caron(Digamma)$], [Ϝ̌], [$caron(digamma)$], [ϝ̌],
      [$caron(Epsilon)$], [Ε̌], [$caron(epsilon)$], [ε̌],
      [--], [--], [$caron(epsilon.alt)$], [ϵ̌],
      [--], [--], [$caron(epsilon.alt.rev)$], [϶̌],
      [--], [--], [$caron(epsilon.rev)$], [϶̌],
      [--], [--], [$caron(epsilon.rev.alt)$], [϶̌],
      [$caron(Eta)$], [Η̌], [$caron(eta)$], [η̌],
      [$caron(Gamma)$], [Γ̌], [$caron(gamma)$], [γ̌],
      [$caron(Iota)$], [Ι̌], [$caron(iota)$], [ι̌],
      [--], [--], [$caron(iota.inv)$], [℩̌],
      [$caron(Kappa)$], [Κ̌], [$caron(kappa)$], [κ̌],
      [--], [--], [$caron(kappa.alt)$], [ϰ̌],
      [$caron(Lambda)$], [Λ̌], [$caron(lambda)$], [λ̌],
      [$caron(Mu)$], [Μ̌], [$caron(mu)$], [μ̌],
      [$caron(Nu)$], [Ν̌], [$caron(nu)$], [ν̌],
      [$caron(Omega)$], [Ω̌], [$caron(omega)$], [ω̌],
      [--], [--], [$caron(Omega.inv)$], [℧̌],
      [$caron(Omicron)$], [Ο̌], [$caron(omicron)$], [ο̌],
      [$caron(Phi)$], [Φ̌], [$caron(phi)$], [φ̌],
      [--], [--], [$caron(phi.alt)$], [ϕ̌],
      [$caron(Pi)$], [Π̌], [$caron(pi)$], [π̌],
      [--], [--], [$caron(pi.alt)$], [ϖ̌],
      [$caron(Psi)$], [Ψ̌], [$caron(psi)$], [ψ̌],
      [$caron(Rho)$], [Ρ̌], [$caron(rho)$], [ρ̌],
      [--], [--], [$caron(rho.alt)$], [ϱ̌],
      [$caron(Sigma)$], [Σ̌], [$caron(sigma)$], [σ̌],
      [--], [--], [$caron(sigma.alt)$], [ς̌],
      [$caron(Tau)$], [Τ̌], [$caron(tau)$], [τ̌],
      [$caron(Theta)$], [Θ̌], [$caron(theta)$], [θ̌],
      [--], [--], [$caron(theta.alt)$], [ϑ̌],
      [--], [--], [$caron(Theta.alt)$], [ϴ̌],
      [$caron(Upsilon)$], [Υ̌], [$caron(upsilon)$], [υ̌],
      [$caron(Xi)$], [Ξ̌], [$caron(xi)$], [ξ̌],
      [$caron(Zeta)$], [Ζ̌], [$caron(zeta)$], [ζ̌],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$caron(0)$], [0̌],
      [$caron(1)$], [1̌],
      [$caron(2)$], [2̌],
      [$caron(3)$], [3̌],
      [$caron(4)$], [4̌],
      [$caron(5)$], [5̌],
      [$caron(6)$], [6̌],
      [$caron(7)$], [7̌],
      [$caron(8)$], [8̌],
      [$caron(9)$], [9̌],
    )
  ],
)

#pagebreak()

= circle

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$circle(A)$], [Å], [$circle(a)$], [å],
      [$circle(B)$], [B̊], [$circle(b)$], [b̊],
      [$circle(C)$], [C̊], [$circle(c)$], [c̊],
      [$circle(D)$], [D̊], [$circle(d)$], [d̊],
      [$circle(E)$], [E̊], [$circle(e)$], [e̊],
      [$circle(F)$], [F̊], [$circle(f)$], [f̊],
      [$circle(G)$], [G̊], [$circle(g)$], [g̊],
      [$circle(H)$], [H̊], [$circle(h)$], [h̊],
      [$circle(I)$], [I̊], [$circle(i)$], [i̊],
      [$circle(J)$], [J̊], [$circle(j)$], [j̊],
      [$circle(K)$], [K̊], [$circle(k)$], [k̊],
      [$circle(L)$], [L̊], [$circle(l)$], [l̊],
      [$circle(M)$], [M̊], [$circle(m)$], [m̊],
      [$circle(N)$], [N̊], [$circle(n)$], [n̊],
      [$circle(O)$], [O̊], [$circle(o)$], [o̊],
      [$circle(P)$], [P̊], [$circle(p)$], [p̊],
      [$circle(Q)$], [Q̊], [$circle(q)$], [q̊],
      [$circle(R)$], [R̊], [$circle(r)$], [r̊],
      [$circle(S)$], [S̊], [$circle(s)$], [s̊],
      [$circle(T)$], [T̊], [$circle(t)$], [t̊],
      [$circle(U)$], [Ů], [$circle(u)$], [ů],
      [$circle(V)$], [V̊], [$circle(v)$], [v̊],
      [$circle(W)$], [W̊], [$circle(w)$], [ẘ],
      [$circle(X)$], [X̊], [$circle(x)$], [x̊],
      [$circle(Y)$], [Y̊], [$circle(y)$], [ẙ],
      [$circle(Z)$], [Z̊], [$circle(z)$], [z̊],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$circle(Alpha)$], [Α̊], [$circle(alpha)$], [α̊],
      [$circle(Beta)$], [Β̊], [$circle(beta)$], [β̊],
      [--], [--], [$circle(beta.alt)$], [ϐ̊],
      [$circle(Chi)$], [Χ̊], [$circle(chi)$], [χ̊],
      [$circle(Delta)$], [Δ̊], [$circle(delta)$], [δ̊],
      [$circle(Digamma)$], [Ϝ̊], [$circle(digamma)$], [ϝ̊],
      [$circle(Epsilon)$], [Ε̊], [$circle(epsilon)$], [ε̊],
      [--], [--], [$circle(epsilon.alt)$], [ϵ̊],
      [--], [--], [$circle(epsilon.alt.rev)$], [϶̊],
      [--], [--], [$circle(epsilon.rev)$], [϶̊],
      [--], [--], [$circle(epsilon.rev.alt)$], [϶̊],
      [$circle(Eta)$], [Η̊], [$circle(eta)$], [η̊],
      [$circle(Gamma)$], [Γ̊], [$circle(gamma)$], [γ̊],
      [$circle(Iota)$], [Ι̊], [$circle(iota)$], [ι̊],
      [--], [--], [$circle(iota.inv)$], [℩̊],
      [$circle(Kappa)$], [Κ̊], [$circle(kappa)$], [κ̊],
      [--], [--], [$circle(kappa.alt)$], [ϰ̊],
      [$circle(Lambda)$], [Λ̊], [$circle(lambda)$], [λ̊],
      [$circle(Mu)$], [Μ̊], [$circle(mu)$], [μ̊],
      [$circle(Nu)$], [Ν̊], [$circle(nu)$], [ν̊],
      [$circle(Omega)$], [Ω̊], [$circle(omega)$], [ω̊],
      [--], [--], [$circle(Omega.inv)$], [℧̊],
      [$circle(Omicron)$], [Ο̊], [$circle(omicron)$], [ο̊],
      [$circle(Phi)$], [Φ̊], [$circle(phi)$], [φ̊],
      [--], [--], [$circle(phi.alt)$], [ϕ̊],
      [$circle(Pi)$], [Π̊], [$circle(pi)$], [π̊],
      [--], [--], [$circle(pi.alt)$], [ϖ̊],
      [$circle(Psi)$], [Ψ̊], [$circle(psi)$], [ψ̊],
      [$circle(Rho)$], [Ρ̊], [$circle(rho)$], [ρ̊],
      [--], [--], [$circle(rho.alt)$], [ϱ̊],
      [$circle(Sigma)$], [Σ̊], [$circle(sigma)$], [σ̊],
      [--], [--], [$circle(sigma.alt)$], [ς̊],
      [$circle(Tau)$], [Τ̊], [$circle(tau)$], [τ̊],
      [$circle(Theta)$], [Θ̊], [$circle(theta)$], [θ̊],
      [--], [--], [$circle(theta.alt)$], [ϑ̊],
      [--], [--], [$circle(Theta.alt)$], [ϴ̊],
      [$circle(Upsilon)$], [Υ̊], [$circle(upsilon)$], [υ̊],
      [$circle(Xi)$], [Ξ̊], [$circle(xi)$], [ξ̊],
      [$circle(Zeta)$], [Ζ̊], [$circle(zeta)$], [ζ̊],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$circle(0)$], [0̊],
      [$circle(1)$], [1̊],
      [$circle(2)$], [2̊],
      [$circle(3)$], [3̊],
      [$circle(4)$], [4̊],
      [$circle(5)$], [5̊],
      [$circle(6)$], [6̊],
      [$circle(7)$], [7̊],
      [$circle(8)$], [8̊],
      [$circle(9)$], [9̊],
    )
  ],
)

#pagebreak()

= dash

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dash(A)$], [A̅], [$dash(a)$], [a̅],
      [$dash(B)$], [B̅], [$dash(b)$], [b̅],
      [$dash(C)$], [C̅], [$dash(c)$], [c̅],
      [$dash(D)$], [D̅], [$dash(d)$], [d̅],
      [$dash(E)$], [E̅], [$dash(e)$], [e̅],
      [$dash(F)$], [F̅], [$dash(f)$], [f̅],
      [$dash(G)$], [G̅], [$dash(g)$], [g̅],
      [$dash(H)$], [H̅], [$dash(h)$], [h̅],
      [$dash(I)$], [I̅], [$dash(i)$], [i̅],
      [$dash(J)$], [J̅], [$dash(j)$], [j̅],
      [$dash(K)$], [K̅], [$dash(k)$], [k̅],
      [$dash(L)$], [L̅], [$dash(l)$], [l̅],
      [$dash(M)$], [M̅], [$dash(m)$], [m̅],
      [$dash(N)$], [N̅], [$dash(n)$], [n̅],
      [$dash(O)$], [O̅], [$dash(o)$], [o̅],
      [$dash(P)$], [P̅], [$dash(p)$], [p̅],
      [$dash(Q)$], [Q̅], [$dash(q)$], [q̅],
      [$dash(R)$], [R̅], [$dash(r)$], [r̅],
      [$dash(S)$], [S̅], [$dash(s)$], [s̅],
      [$dash(T)$], [T̅], [$dash(t)$], [t̅],
      [$dash(U)$], [U̅], [$dash(u)$], [u̅],
      [$dash(V)$], [V̅], [$dash(v)$], [v̅],
      [$dash(W)$], [W̅], [$dash(w)$], [w̅],
      [$dash(X)$], [X̅], [$dash(x)$], [x̅],
      [$dash(Y)$], [Y̅], [$dash(y)$], [y̅],
      [$dash(Z)$], [Z̅], [$dash(z)$], [z̅],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dash(Alpha)$], [Α̅], [$dash(alpha)$], [α̅],
      [$dash(Beta)$], [Β̅], [$dash(beta)$], [β̅],
      [--], [--], [$dash(beta.alt)$], [ϐ̅],
      [$dash(Chi)$], [Χ̅], [$dash(chi)$], [χ̅],
      [$dash(Delta)$], [Δ̅], [$dash(delta)$], [δ̅],
      [$dash(Digamma)$], [Ϝ̅], [$dash(digamma)$], [ϝ̅],
      [$dash(Epsilon)$], [Ε̅], [$dash(epsilon)$], [ε̅],
      [--], [--], [$dash(epsilon.alt)$], [ϵ̅],
      [--], [--], [$dash(epsilon.alt.rev)$], [϶̅],
      [--], [--], [$dash(epsilon.rev)$], [϶̅],
      [--], [--], [$dash(epsilon.rev.alt)$], [϶̅],
      [$dash(Eta)$], [Η̅], [$dash(eta)$], [η̅],
      [$dash(Gamma)$], [Γ̅], [$dash(gamma)$], [γ̅],
      [$dash(Iota)$], [Ι̅], [$dash(iota)$], [ι̅],
      [--], [--], [$dash(iota.inv)$], [℩̅],
      [$dash(Kappa)$], [Κ̅], [$dash(kappa)$], [κ̅],
      [--], [--], [$dash(kappa.alt)$], [ϰ̅],
      [$dash(Lambda)$], [Λ̅], [$dash(lambda)$], [λ̅],
      [$dash(Mu)$], [Μ̅], [$dash(mu)$], [μ̅],
      [$dash(Nu)$], [Ν̅], [$dash(nu)$], [ν̅],
      [$dash(Omega)$], [Ω̅], [$dash(omega)$], [ω̅],
      [--], [--], [$dash(Omega.inv)$], [℧̅],
      [$dash(Omicron)$], [Ο̅], [$dash(omicron)$], [ο̅],
      [$dash(Phi)$], [Φ̅], [$dash(phi)$], [φ̅],
      [--], [--], [$dash(phi.alt)$], [ϕ̅],
      [$dash(Pi)$], [Π̅], [$dash(pi)$], [π̅],
      [--], [--], [$dash(pi.alt)$], [ϖ̅],
      [$dash(Psi)$], [Ψ̅], [$dash(psi)$], [ψ̅],
      [$dash(Rho)$], [Ρ̅], [$dash(rho)$], [ρ̅],
      [--], [--], [$dash(rho.alt)$], [ϱ̅],
      [$dash(Sigma)$], [Σ̅], [$dash(sigma)$], [σ̅],
      [--], [--], [$dash(sigma.alt)$], [ς̅],
      [$dash(Tau)$], [Τ̅], [$dash(tau)$], [τ̅],
      [$dash(Theta)$], [Θ̅], [$dash(theta)$], [θ̅],
      [--], [--], [$dash(theta.alt)$], [ϑ̅],
      [--], [--], [$dash(Theta.alt)$], [ϴ̅],
      [$dash(Upsilon)$], [Υ̅], [$dash(upsilon)$], [υ̅],
      [$dash(Xi)$], [Ξ̅], [$dash(xi)$], [ξ̅],
      [$dash(Zeta)$], [Ζ̅], [$dash(zeta)$], [ζ̅],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$dash(0)$], [0̅],
      [$dash(1)$], [1̅],
      [$dash(2)$], [2̅],
      [$dash(3)$], [3̅],
      [$dash(4)$], [4̅],
      [$dash(5)$], [5̅],
      [$dash(6)$], [6̅],
      [$dash(7)$], [7̅],
      [$dash(8)$], [8̅],
      [$dash(9)$], [9̅],
    )
  ],
)

#pagebreak()

= diaer

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$diaer(A)$], [Ä], [$diaer(a)$], [ä],
      [$diaer(B)$], [B̈], [$diaer(b)$], [b̈],
      [$diaer(C)$], [C̈], [$diaer(c)$], [c̈],
      [$diaer(D)$], [D̈], [$diaer(d)$], [d̈],
      [$diaer(E)$], [Ë], [$diaer(e)$], [ë],
      [$diaer(F)$], [F̈], [$diaer(f)$], [f̈],
      [$diaer(G)$], [G̈], [$diaer(g)$], [g̈],
      [$diaer(H)$], [Ḧ], [$diaer(h)$], [ḧ],
      [$diaer(I)$], [Ï], [$diaer(i)$], [ï],
      [$diaer(J)$], [J̈], [$diaer(j)$], [j̈],
      [$diaer(K)$], [K̈], [$diaer(k)$], [k̈],
      [$diaer(L)$], [L̈], [$diaer(l)$], [l̈],
      [$diaer(M)$], [M̈], [$diaer(m)$], [m̈],
      [$diaer(N)$], [N̈], [$diaer(n)$], [n̈],
      [$diaer(O)$], [Ö], [$diaer(o)$], [ö],
      [$diaer(P)$], [P̈], [$diaer(p)$], [p̈],
      [$diaer(Q)$], [Q̈], [$diaer(q)$], [q̈],
      [$diaer(R)$], [R̈], [$diaer(r)$], [r̈],
      [$diaer(S)$], [S̈], [$diaer(s)$], [s̈],
      [$diaer(T)$], [T̈], [$diaer(t)$], [ẗ],
      [$diaer(U)$], [Ü], [$diaer(u)$], [ü],
      [$diaer(V)$], [V̈], [$diaer(v)$], [v̈],
      [$diaer(W)$], [Ẅ], [$diaer(w)$], [ẅ],
      [$diaer(X)$], [Ẍ], [$diaer(x)$], [ẍ],
      [$diaer(Y)$], [Ÿ], [$diaer(y)$], [ÿ],
      [$diaer(Z)$], [Z̈], [$diaer(z)$], [z̈],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$diaer(Alpha)$], [Α̈], [$diaer(alpha)$], [α̈],
      [$diaer(Beta)$], [Β̈], [$diaer(beta)$], [β̈],
      [--], [--], [$diaer(beta.alt)$], [ϐ̈],
      [$diaer(Chi)$], [Χ̈], [$diaer(chi)$], [χ̈],
      [$diaer(Delta)$], [Δ̈], [$diaer(delta)$], [δ̈],
      [$diaer(Digamma)$], [Ϝ̈], [$diaer(digamma)$], [ϝ̈],
      [$diaer(Epsilon)$], [Ε̈], [$diaer(epsilon)$], [ε̈],
      [--], [--], [$diaer(epsilon.alt)$], [ϵ̈],
      [--], [--], [$diaer(epsilon.alt.rev)$], [϶̈],
      [--], [--], [$diaer(epsilon.rev)$], [϶̈],
      [--], [--], [$diaer(epsilon.rev.alt)$], [϶̈],
      [$diaer(Eta)$], [Η̈], [$diaer(eta)$], [η̈],
      [$diaer(Gamma)$], [Γ̈], [$diaer(gamma)$], [γ̈],
      [$diaer(Iota)$], [Ϊ], [$diaer(iota)$], [ϊ],
      [--], [--], [$diaer(iota.inv)$], [℩̈],
      [$diaer(Kappa)$], [Κ̈], [$diaer(kappa)$], [κ̈],
      [--], [--], [$diaer(kappa.alt)$], [ϰ̈],
      [$diaer(Lambda)$], [Λ̈], [$diaer(lambda)$], [λ̈],
      [$diaer(Mu)$], [Μ̈], [$diaer(mu)$], [μ̈],
      [$diaer(Nu)$], [Ν̈], [$diaer(nu)$], [ν̈],
      [$diaer(Omega)$], [Ω̈], [$diaer(omega)$], [ω̈],
      [--], [--], [$diaer(Omega.inv)$], [℧̈],
      [$diaer(Omicron)$], [Ο̈], [$diaer(omicron)$], [ο̈],
      [$diaer(Phi)$], [Φ̈], [$diaer(phi)$], [φ̈],
      [--], [--], [$diaer(phi.alt)$], [ϕ̈],
      [$diaer(Pi)$], [Π̈], [$diaer(pi)$], [π̈],
      [--], [--], [$diaer(pi.alt)$], [ϖ̈],
      [$diaer(Psi)$], [Ψ̈], [$diaer(psi)$], [ψ̈],
      [$diaer(Rho)$], [Ρ̈], [$diaer(rho)$], [ρ̈],
      [--], [--], [$diaer(rho.alt)$], [ϱ̈],
      [$diaer(Sigma)$], [Σ̈], [$diaer(sigma)$], [σ̈],
      [--], [--], [$diaer(sigma.alt)$], [ς̈],
      [$diaer(Tau)$], [Τ̈], [$diaer(tau)$], [τ̈],
      [$diaer(Theta)$], [Θ̈], [$diaer(theta)$], [θ̈],
      [--], [--], [$diaer(theta.alt)$], [ϑ̈],
      [--], [--], [$diaer(Theta.alt)$], [ϴ̈],
      [$diaer(Upsilon)$], [Ϋ], [$diaer(upsilon)$], [ϋ],
      [$diaer(Xi)$], [Ξ̈], [$diaer(xi)$], [ξ̈],
      [$diaer(Zeta)$], [Ζ̈], [$diaer(zeta)$], [ζ̈],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$diaer(0)$], [0̈],
      [$diaer(1)$], [1̈],
      [$diaer(2)$], [2̈],
      [$diaer(3)$], [3̈],
      [$diaer(4)$], [4̈],
      [$diaer(5)$], [5̈],
      [$diaer(6)$], [6̈],
      [$diaer(7)$], [7̈],
      [$diaer(8)$], [8̈],
      [$diaer(9)$], [9̈],
    )
  ],
)

#pagebreak()

= dot

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot(A)$], [Ȧ], [$dot(a)$], [ȧ],
      [$dot(B)$], [Ḃ], [$dot(b)$], [ḃ],
      [$dot(C)$], [Ċ], [$dot(c)$], [ċ],
      [$dot(D)$], [Ḋ], [$dot(d)$], [ḋ],
      [$dot(E)$], [Ė], [$dot(e)$], [ė],
      [$dot(F)$], [Ḟ], [$dot(f)$], [ḟ],
      [$dot(G)$], [Ġ], [$dot(g)$], [ġ],
      [$dot(H)$], [Ḣ], [$dot(h)$], [ḣ],
      [$dot(I)$], [İ], [$dot(i)$], [i̇],
      [$dot(J)$], [J̇], [$dot(j)$], [j̇],
      [$dot(K)$], [K̇], [$dot(k)$], [k̇],
      [$dot(L)$], [L̇], [$dot(l)$], [l̇],
      [$dot(M)$], [Ṁ], [$dot(m)$], [ṁ],
      [$dot(N)$], [Ṅ], [$dot(n)$], [ṅ],
      [$dot(O)$], [Ȯ], [$dot(o)$], [ȯ],
      [$dot(P)$], [Ṗ], [$dot(p)$], [ṗ],
      [$dot(Q)$], [Q̇], [$dot(q)$], [q̇],
      [$dot(R)$], [Ṙ], [$dot(r)$], [ṙ],
      [$dot(S)$], [Ṡ], [$dot(s)$], [ṡ],
      [$dot(T)$], [Ṫ], [$dot(t)$], [ṫ],
      [$dot(U)$], [U̇], [$dot(u)$], [u̇],
      [$dot(V)$], [V̇], [$dot(v)$], [v̇],
      [$dot(W)$], [Ẇ], [$dot(w)$], [ẇ],
      [$dot(X)$], [Ẋ], [$dot(x)$], [ẋ],
      [$dot(Y)$], [Ẏ], [$dot(y)$], [ẏ],
      [$dot(Z)$], [Ż], [$dot(z)$], [ż],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot(Alpha)$], [Α̇], [$dot(alpha)$], [α̇],
      [$dot(Beta)$], [Β̇], [$dot(beta)$], [β̇],
      [--], [--], [$dot(beta.alt)$], [ϐ̇],
      [$dot(Chi)$], [Χ̇], [$dot(chi)$], [χ̇],
      [$dot(Delta)$], [Δ̇], [$dot(delta)$], [δ̇],
      [$dot(Digamma)$], [Ϝ̇], [$dot(digamma)$], [ϝ̇],
      [$dot(Epsilon)$], [Ε̇], [$dot(epsilon)$], [ε̇],
      [--], [--], [$dot(epsilon.alt)$], [ϵ̇],
      [--], [--], [$dot(epsilon.alt.rev)$], [϶̇],
      [--], [--], [$dot(epsilon.rev)$], [϶̇],
      [--], [--], [$dot(epsilon.rev.alt)$], [϶̇],
      [$dot(Eta)$], [Η̇], [$dot(eta)$], [η̇],
      [$dot(Gamma)$], [Γ̇], [$dot(gamma)$], [γ̇],
      [$dot(Iota)$], [Ι̇], [$dot(iota)$], [ι̇],
      [--], [--], [$dot(iota.inv)$], [℩̇],
      [$dot(Kappa)$], [Κ̇], [$dot(kappa)$], [κ̇],
      [--], [--], [$dot(kappa.alt)$], [ϰ̇],
      [$dot(Lambda)$], [Λ̇], [$dot(lambda)$], [λ̇],
      [$dot(Mu)$], [Μ̇], [$dot(mu)$], [μ̇],
      [$dot(Nu)$], [Ν̇], [$dot(nu)$], [ν̇],
      [$dot(Omega)$], [Ω̇], [$dot(omega)$], [ω̇],
      [--], [--], [$dot(Omega.inv)$], [℧̇],
      [$dot(Omicron)$], [Ο̇], [$dot(omicron)$], [ο̇],
      [$dot(Phi)$], [Φ̇], [$dot(phi)$], [φ̇],
      [--], [--], [$dot(phi.alt)$], [ϕ̇],
      [$dot(Pi)$], [Π̇], [$dot(pi)$], [π̇],
      [--], [--], [$dot(pi.alt)$], [ϖ̇],
      [$dot(Psi)$], [Ψ̇], [$dot(psi)$], [ψ̇],
      [$dot(Rho)$], [Ρ̇], [$dot(rho)$], [ρ̇],
      [--], [--], [$dot(rho.alt)$], [ϱ̇],
      [$dot(Sigma)$], [Σ̇], [$dot(sigma)$], [σ̇],
      [--], [--], [$dot(sigma.alt)$], [ς̇],
      [$dot(Tau)$], [Τ̇], [$dot(tau)$], [τ̇],
      [$dot(Theta)$], [Θ̇], [$dot(theta)$], [θ̇],
      [--], [--], [$dot(theta.alt)$], [ϑ̇],
      [--], [--], [$dot(Theta.alt)$], [ϴ̇],
      [$dot(Upsilon)$], [Υ̇], [$dot(upsilon)$], [υ̇],
      [$dot(Xi)$], [Ξ̇], [$dot(xi)$], [ξ̇],
      [$dot(Zeta)$], [Ζ̇], [$dot(zeta)$], [ζ̇],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$dot(0)$], [0̇],
      [$dot(1)$], [1̇],
      [$dot(2)$], [2̇],
      [$dot(3)$], [3̇],
      [$dot(4)$], [4̇],
      [$dot(5)$], [5̇],
      [$dot(6)$], [6̇],
      [$dot(7)$], [7̇],
      [$dot(8)$], [8̇],
      [$dot(9)$], [9̇],
    )
  ],
)

#pagebreak()

= dot.double

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot.double(A)$], [Ä], [$dot.double(a)$], [ä],
      [$dot.double(B)$], [B̈], [$dot.double(b)$], [b̈],
      [$dot.double(C)$], [C̈], [$dot.double(c)$], [c̈],
      [$dot.double(D)$], [D̈], [$dot.double(d)$], [d̈],
      [$dot.double(E)$], [Ë], [$dot.double(e)$], [ë],
      [$dot.double(F)$], [F̈], [$dot.double(f)$], [f̈],
      [$dot.double(G)$], [G̈], [$dot.double(g)$], [g̈],
      [$dot.double(H)$], [Ḧ], [$dot.double(h)$], [ḧ],
      [$dot.double(I)$], [Ï], [$dot.double(i)$], [ï],
      [$dot.double(J)$], [J̈], [$dot.double(j)$], [j̈],
      [$dot.double(K)$], [K̈], [$dot.double(k)$], [k̈],
      [$dot.double(L)$], [L̈], [$dot.double(l)$], [l̈],
      [$dot.double(M)$], [M̈], [$dot.double(m)$], [m̈],
      [$dot.double(N)$], [N̈], [$dot.double(n)$], [n̈],
      [$dot.double(O)$], [Ö], [$dot.double(o)$], [ö],
      [$dot.double(P)$], [P̈], [$dot.double(p)$], [p̈],
      [$dot.double(Q)$], [Q̈], [$dot.double(q)$], [q̈],
      [$dot.double(R)$], [R̈], [$dot.double(r)$], [r̈],
      [$dot.double(S)$], [S̈], [$dot.double(s)$], [s̈],
      [$dot.double(T)$], [T̈], [$dot.double(t)$], [ẗ],
      [$dot.double(U)$], [Ü], [$dot.double(u)$], [ü],
      [$dot.double(V)$], [V̈], [$dot.double(v)$], [v̈],
      [$dot.double(W)$], [Ẅ], [$dot.double(w)$], [ẅ],
      [$dot.double(X)$], [Ẍ], [$dot.double(x)$], [ẍ],
      [$dot.double(Y)$], [Ÿ], [$dot.double(y)$], [ÿ],
      [$dot.double(Z)$], [Z̈], [$dot.double(z)$], [z̈],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot.double(Alpha)$], [Α̈], [$dot.double(alpha)$], [α̈],
      [$dot.double(Beta)$], [Β̈], [$dot.double(beta)$], [β̈],
      [--], [--], [$dot.double(beta.alt)$], [ϐ̈],
      [$dot.double(Chi)$], [Χ̈], [$dot.double(chi)$], [χ̈],
      [$dot.double(Delta)$], [Δ̈], [$dot.double(delta)$], [δ̈],
      [$dot.double(Digamma)$], [Ϝ̈], [$dot.double(digamma)$], [ϝ̈],
      [$dot.double(Epsilon)$], [Ε̈], [$dot.double(epsilon)$], [ε̈],
      [--], [--], [$dot.double(epsilon.alt)$], [ϵ̈],
      [--], [--], [$dot.double(epsilon.alt.rev)$], [϶̈],
      [--], [--], [$dot.double(epsilon.rev)$], [϶̈],
      [--], [--], [$dot.double(epsilon.rev.alt)$], [϶̈],
      [$dot.double(Eta)$], [Η̈], [$dot.double(eta)$], [η̈],
      [$dot.double(Gamma)$], [Γ̈], [$dot.double(gamma)$], [γ̈],
      [$dot.double(Iota)$], [Ϊ], [$dot.double(iota)$], [ϊ],
      [--], [--], [$dot.double(iota.inv)$], [℩̈],
      [$dot.double(Kappa)$], [Κ̈], [$dot.double(kappa)$], [κ̈],
      [--], [--], [$dot.double(kappa.alt)$], [ϰ̈],
      [$dot.double(Lambda)$], [Λ̈], [$dot.double(lambda)$], [λ̈],
      [$dot.double(Mu)$], [Μ̈], [$dot.double(mu)$], [μ̈],
      [$dot.double(Nu)$], [Ν̈], [$dot.double(nu)$], [ν̈],
      [$dot.double(Omega)$], [Ω̈], [$dot.double(omega)$], [ω̈],
      [--], [--], [$dot.double(Omega.inv)$], [℧̈],
      [$dot.double(Omicron)$], [Ο̈], [$dot.double(omicron)$], [ο̈],
      [$dot.double(Phi)$], [Φ̈], [$dot.double(phi)$], [φ̈],
      [--], [--], [$dot.double(phi.alt)$], [ϕ̈],
      [$dot.double(Pi)$], [Π̈], [$dot.double(pi)$], [π̈],
      [--], [--], [$dot.double(pi.alt)$], [ϖ̈],
      [$dot.double(Psi)$], [Ψ̈], [$dot.double(psi)$], [ψ̈],
      [$dot.double(Rho)$], [Ρ̈], [$dot.double(rho)$], [ρ̈],
      [--], [--], [$dot.double(rho.alt)$], [ϱ̈],
      [$dot.double(Sigma)$], [Σ̈], [$dot.double(sigma)$], [σ̈],
      [--], [--], [$dot.double(sigma.alt)$], [ς̈],
      [$dot.double(Tau)$], [Τ̈], [$dot.double(tau)$], [τ̈],
      [$dot.double(Theta)$], [Θ̈], [$dot.double(theta)$], [θ̈],
      [--], [--], [$dot.double(theta.alt)$], [ϑ̈],
      [--], [--], [$dot.double(Theta.alt)$], [ϴ̈],
      [$dot.double(Upsilon)$], [Ϋ], [$dot.double(upsilon)$], [ϋ],
      [$dot.double(Xi)$], [Ξ̈], [$dot.double(xi)$], [ξ̈],
      [$dot.double(Zeta)$], [Ζ̈], [$dot.double(zeta)$], [ζ̈],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$dot.double(0)$], [0̈],
      [$dot.double(1)$], [1̈],
      [$dot.double(2)$], [2̈],
      [$dot.double(3)$], [3̈],
      [$dot.double(4)$], [4̈],
      [$dot.double(5)$], [5̈],
      [$dot.double(6)$], [6̈],
      [$dot.double(7)$], [7̈],
      [$dot.double(8)$], [8̈],
      [$dot.double(9)$], [9̈],
    )
  ],
)

#pagebreak()

= dot.quad

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot.quad(A)$], [A⃜], [$dot.quad(a)$], [a⃜],
      [$dot.quad(B)$], [B⃜], [$dot.quad(b)$], [b⃜],
      [$dot.quad(C)$], [C⃜], [$dot.quad(c)$], [c⃜],
      [$dot.quad(D)$], [D⃜], [$dot.quad(d)$], [d⃜],
      [$dot.quad(E)$], [E⃜], [$dot.quad(e)$], [e⃜],
      [$dot.quad(F)$], [F⃜], [$dot.quad(f)$], [f⃜],
      [$dot.quad(G)$], [G⃜], [$dot.quad(g)$], [g⃜],
      [$dot.quad(H)$], [H⃜], [$dot.quad(h)$], [h⃜],
      [$dot.quad(I)$], [I⃜], [$dot.quad(i)$], [i⃜],
      [$dot.quad(J)$], [J⃜], [$dot.quad(j)$], [j⃜],
      [$dot.quad(K)$], [K⃜], [$dot.quad(k)$], [k⃜],
      [$dot.quad(L)$], [L⃜], [$dot.quad(l)$], [l⃜],
      [$dot.quad(M)$], [M⃜], [$dot.quad(m)$], [m⃜],
      [$dot.quad(N)$], [N⃜], [$dot.quad(n)$], [n⃜],
      [$dot.quad(O)$], [O⃜], [$dot.quad(o)$], [o⃜],
      [$dot.quad(P)$], [P⃜], [$dot.quad(p)$], [p⃜],
      [$dot.quad(Q)$], [Q⃜], [$dot.quad(q)$], [q⃜],
      [$dot.quad(R)$], [R⃜], [$dot.quad(r)$], [r⃜],
      [$dot.quad(S)$], [S⃜], [$dot.quad(s)$], [s⃜],
      [$dot.quad(T)$], [T⃜], [$dot.quad(t)$], [t⃜],
      [$dot.quad(U)$], [U⃜], [$dot.quad(u)$], [u⃜],
      [$dot.quad(V)$], [V⃜], [$dot.quad(v)$], [v⃜],
      [$dot.quad(W)$], [W⃜], [$dot.quad(w)$], [w⃜],
      [$dot.quad(X)$], [X⃜], [$dot.quad(x)$], [x⃜],
      [$dot.quad(Y)$], [Y⃜], [$dot.quad(y)$], [y⃜],
      [$dot.quad(Z)$], [Z⃜], [$dot.quad(z)$], [z⃜],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot.quad(Alpha)$], [Α⃜], [$dot.quad(alpha)$], [α⃜],
      [$dot.quad(Beta)$], [Β⃜], [$dot.quad(beta)$], [β⃜],
      [--], [--], [$dot.quad(beta.alt)$], [ϐ⃜],
      [$dot.quad(Chi)$], [Χ⃜], [$dot.quad(chi)$], [χ⃜],
      [$dot.quad(Delta)$], [Δ⃜], [$dot.quad(delta)$], [δ⃜],
      [$dot.quad(Digamma)$], [Ϝ⃜], [$dot.quad(digamma)$], [ϝ⃜],
      [$dot.quad(Epsilon)$], [Ε⃜], [$dot.quad(epsilon)$], [ε⃜],
      [--], [--], [$dot.quad(epsilon.alt)$], [ϵ⃜],
      [--], [--], [$dot.quad(epsilon.alt.rev)$], [϶⃜],
      [--], [--], [$dot.quad(epsilon.rev)$], [϶⃜],
      [--], [--], [$dot.quad(epsilon.rev.alt)$], [϶⃜],
      [$dot.quad(Eta)$], [Η⃜], [$dot.quad(eta)$], [η⃜],
      [$dot.quad(Gamma)$], [Γ⃜], [$dot.quad(gamma)$], [γ⃜],
      [$dot.quad(Iota)$], [Ι⃜], [$dot.quad(iota)$], [ι⃜],
      [--], [--], [$dot.quad(iota.inv)$], [℩⃜],
      [$dot.quad(Kappa)$], [Κ⃜], [$dot.quad(kappa)$], [κ⃜],
      [--], [--], [$dot.quad(kappa.alt)$], [ϰ⃜],
      [$dot.quad(Lambda)$], [Λ⃜], [$dot.quad(lambda)$], [λ⃜],
      [$dot.quad(Mu)$], [Μ⃜], [$dot.quad(mu)$], [μ⃜],
      [$dot.quad(Nu)$], [Ν⃜], [$dot.quad(nu)$], [ν⃜],
      [$dot.quad(Omega)$], [Ω⃜], [$dot.quad(omega)$], [ω⃜],
      [--], [--], [$dot.quad(Omega.inv)$], [℧⃜],
      [$dot.quad(Omicron)$], [Ο⃜], [$dot.quad(omicron)$], [ο⃜],
      [$dot.quad(Phi)$], [Φ⃜], [$dot.quad(phi)$], [φ⃜],
      [--], [--], [$dot.quad(phi.alt)$], [ϕ⃜],
      [$dot.quad(Pi)$], [Π⃜], [$dot.quad(pi)$], [π⃜],
      [--], [--], [$dot.quad(pi.alt)$], [ϖ⃜],
      [$dot.quad(Psi)$], [Ψ⃜], [$dot.quad(psi)$], [ψ⃜],
      [$dot.quad(Rho)$], [Ρ⃜], [$dot.quad(rho)$], [ρ⃜],
      [--], [--], [$dot.quad(rho.alt)$], [ϱ⃜],
      [$dot.quad(Sigma)$], [Σ⃜], [$dot.quad(sigma)$], [σ⃜],
      [--], [--], [$dot.quad(sigma.alt)$], [ς⃜],
      [$dot.quad(Tau)$], [Τ⃜], [$dot.quad(tau)$], [τ⃜],
      [$dot.quad(Theta)$], [Θ⃜], [$dot.quad(theta)$], [θ⃜],
      [--], [--], [$dot.quad(theta.alt)$], [ϑ⃜],
      [--], [--], [$dot.quad(Theta.alt)$], [ϴ⃜],
      [$dot.quad(Upsilon)$], [Υ⃜], [$dot.quad(upsilon)$], [υ⃜],
      [$dot.quad(Xi)$], [Ξ⃜], [$dot.quad(xi)$], [ξ⃜],
      [$dot.quad(Zeta)$], [Ζ⃜], [$dot.quad(zeta)$], [ζ⃜],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$dot.quad(0)$], [0⃜],
      [$dot.quad(1)$], [1⃜],
      [$dot.quad(2)$], [2⃜],
      [$dot.quad(3)$], [3⃜],
      [$dot.quad(4)$], [4⃜],
      [$dot.quad(5)$], [5⃜],
      [$dot.quad(6)$], [6⃜],
      [$dot.quad(7)$], [7⃜],
      [$dot.quad(8)$], [8⃜],
      [$dot.quad(9)$], [9⃜],
    )
  ],
)

#pagebreak()

= dot.triple

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot.triple(A)$], [A⃛], [$dot.triple(a)$], [a⃛],
      [$dot.triple(B)$], [B⃛], [$dot.triple(b)$], [b⃛],
      [$dot.triple(C)$], [C⃛], [$dot.triple(c)$], [c⃛],
      [$dot.triple(D)$], [D⃛], [$dot.triple(d)$], [d⃛],
      [$dot.triple(E)$], [E⃛], [$dot.triple(e)$], [e⃛],
      [$dot.triple(F)$], [F⃛], [$dot.triple(f)$], [f⃛],
      [$dot.triple(G)$], [G⃛], [$dot.triple(g)$], [g⃛],
      [$dot.triple(H)$], [H⃛], [$dot.triple(h)$], [h⃛],
      [$dot.triple(I)$], [I⃛], [$dot.triple(i)$], [i⃛],
      [$dot.triple(J)$], [J⃛], [$dot.triple(j)$], [j⃛],
      [$dot.triple(K)$], [K⃛], [$dot.triple(k)$], [k⃛],
      [$dot.triple(L)$], [L⃛], [$dot.triple(l)$], [l⃛],
      [$dot.triple(M)$], [M⃛], [$dot.triple(m)$], [m⃛],
      [$dot.triple(N)$], [N⃛], [$dot.triple(n)$], [n⃛],
      [$dot.triple(O)$], [O⃛], [$dot.triple(o)$], [o⃛],
      [$dot.triple(P)$], [P⃛], [$dot.triple(p)$], [p⃛],
      [$dot.triple(Q)$], [Q⃛], [$dot.triple(q)$], [q⃛],
      [$dot.triple(R)$], [R⃛], [$dot.triple(r)$], [r⃛],
      [$dot.triple(S)$], [S⃛], [$dot.triple(s)$], [s⃛],
      [$dot.triple(T)$], [T⃛], [$dot.triple(t)$], [t⃛],
      [$dot.triple(U)$], [U⃛], [$dot.triple(u)$], [u⃛],
      [$dot.triple(V)$], [V⃛], [$dot.triple(v)$], [v⃛],
      [$dot.triple(W)$], [W⃛], [$dot.triple(w)$], [w⃛],
      [$dot.triple(X)$], [X⃛], [$dot.triple(x)$], [x⃛],
      [$dot.triple(Y)$], [Y⃛], [$dot.triple(y)$], [y⃛],
      [$dot.triple(Z)$], [Z⃛], [$dot.triple(z)$], [z⃛],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$dot.triple(Alpha)$], [Α⃛], [$dot.triple(alpha)$], [α⃛],
      [$dot.triple(Beta)$], [Β⃛], [$dot.triple(beta)$], [β⃛],
      [--], [--], [$dot.triple(beta.alt)$], [ϐ⃛],
      [$dot.triple(Chi)$], [Χ⃛], [$dot.triple(chi)$], [χ⃛],
      [$dot.triple(Delta)$], [Δ⃛], [$dot.triple(delta)$], [δ⃛],
      [$dot.triple(Digamma)$], [Ϝ⃛], [$dot.triple(digamma)$], [ϝ⃛],
      [$dot.triple(Epsilon)$], [Ε⃛], [$dot.triple(epsilon)$], [ε⃛],
      [--], [--], [$dot.triple(epsilon.alt)$], [ϵ⃛],
      [--], [--], [$dot.triple(epsilon.alt.rev)$], [϶⃛],
      [--], [--], [$dot.triple(epsilon.rev)$], [϶⃛],
      [--], [--], [$dot.triple(epsilon.rev.alt)$], [϶⃛],
      [$dot.triple(Eta)$], [Η⃛], [$dot.triple(eta)$], [η⃛],
      [$dot.triple(Gamma)$], [Γ⃛], [$dot.triple(gamma)$], [γ⃛],
      [$dot.triple(Iota)$], [Ι⃛], [$dot.triple(iota)$], [ι⃛],
      [--], [--], [$dot.triple(iota.inv)$], [℩⃛],
      [$dot.triple(Kappa)$], [Κ⃛], [$dot.triple(kappa)$], [κ⃛],
      [--], [--], [$dot.triple(kappa.alt)$], [ϰ⃛],
      [$dot.triple(Lambda)$], [Λ⃛], [$dot.triple(lambda)$], [λ⃛],
      [$dot.triple(Mu)$], [Μ⃛], [$dot.triple(mu)$], [μ⃛],
      [$dot.triple(Nu)$], [Ν⃛], [$dot.triple(nu)$], [ν⃛],
      [$dot.triple(Omega)$], [Ω⃛], [$dot.triple(omega)$], [ω⃛],
      [--], [--], [$dot.triple(Omega.inv)$], [℧⃛],
      [$dot.triple(Omicron)$], [Ο⃛], [$dot.triple(omicron)$], [ο⃛],
      [$dot.triple(Phi)$], [Φ⃛], [$dot.triple(phi)$], [φ⃛],
      [--], [--], [$dot.triple(phi.alt)$], [ϕ⃛],
      [$dot.triple(Pi)$], [Π⃛], [$dot.triple(pi)$], [π⃛],
      [--], [--], [$dot.triple(pi.alt)$], [ϖ⃛],
      [$dot.triple(Psi)$], [Ψ⃛], [$dot.triple(psi)$], [ψ⃛],
      [$dot.triple(Rho)$], [Ρ⃛], [$dot.triple(rho)$], [ρ⃛],
      [--], [--], [$dot.triple(rho.alt)$], [ϱ⃛],
      [$dot.triple(Sigma)$], [Σ⃛], [$dot.triple(sigma)$], [σ⃛],
      [--], [--], [$dot.triple(sigma.alt)$], [ς⃛],
      [$dot.triple(Tau)$], [Τ⃛], [$dot.triple(tau)$], [τ⃛],
      [$dot.triple(Theta)$], [Θ⃛], [$dot.triple(theta)$], [θ⃛],
      [--], [--], [$dot.triple(theta.alt)$], [ϑ⃛],
      [--], [--], [$dot.triple(Theta.alt)$], [ϴ⃛],
      [$dot.triple(Upsilon)$], [Υ⃛], [$dot.triple(upsilon)$], [υ⃛],
      [$dot.triple(Xi)$], [Ξ⃛], [$dot.triple(xi)$], [ξ⃛],
      [$dot.triple(Zeta)$], [Ζ⃛], [$dot.triple(zeta)$], [ζ⃛],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$dot.triple(0)$], [0⃛],
      [$dot.triple(1)$], [1⃛],
      [$dot.triple(2)$], [2⃛],
      [$dot.triple(3)$], [3⃛],
      [$dot.triple(4)$], [4⃛],
      [$dot.triple(5)$], [5⃛],
      [$dot.triple(6)$], [6⃛],
      [$dot.triple(7)$], [7⃛],
      [$dot.triple(8)$], [8⃛],
      [$dot.triple(9)$], [9⃛],
    )
  ],
)

#pagebreak()

= grave

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$grave(A)$], [À], [$grave(a)$], [à],
      [$grave(B)$], [B̀], [$grave(b)$], [b̀],
      [$grave(C)$], [C̀], [$grave(c)$], [c̀],
      [$grave(D)$], [D̀], [$grave(d)$], [d̀],
      [$grave(E)$], [È], [$grave(e)$], [è],
      [$grave(F)$], [F̀], [$grave(f)$], [f̀],
      [$grave(G)$], [G̀], [$grave(g)$], [g̀],
      [$grave(H)$], [H̀], [$grave(h)$], [h̀],
      [$grave(I)$], [Ì], [$grave(i)$], [ì],
      [$grave(J)$], [J̀], [$grave(j)$], [j̀],
      [$grave(K)$], [K̀], [$grave(k)$], [k̀],
      [$grave(L)$], [L̀], [$grave(l)$], [l̀],
      [$grave(M)$], [M̀], [$grave(m)$], [m̀],
      [$grave(N)$], [Ǹ], [$grave(n)$], [ǹ],
      [$grave(O)$], [Ò], [$grave(o)$], [ò],
      [$grave(P)$], [P̀], [$grave(p)$], [p̀],
      [$grave(Q)$], [Q̀], [$grave(q)$], [q̀],
      [$grave(R)$], [R̀], [$grave(r)$], [r̀],
      [$grave(S)$], [S̀], [$grave(s)$], [s̀],
      [$grave(T)$], [T̀], [$grave(t)$], [t̀],
      [$grave(U)$], [Ù], [$grave(u)$], [ù],
      [$grave(V)$], [V̀], [$grave(v)$], [v̀],
      [$grave(W)$], [Ẁ], [$grave(w)$], [ẁ],
      [$grave(X)$], [X̀], [$grave(x)$], [x̀],
      [$grave(Y)$], [Ỳ], [$grave(y)$], [ỳ],
      [$grave(Z)$], [Z̀], [$grave(z)$], [z̀],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$grave(Alpha)$], [Ὰ], [$grave(alpha)$], [ὰ],
      [$grave(Beta)$], [Β̀], [$grave(beta)$], [β̀],
      [--], [--], [$grave(beta.alt)$], [ϐ̀],
      [$grave(Chi)$], [Χ̀], [$grave(chi)$], [χ̀],
      [$grave(Delta)$], [Δ̀], [$grave(delta)$], [δ̀],
      [$grave(Digamma)$], [Ϝ̀], [$grave(digamma)$], [ϝ̀],
      [$grave(Epsilon)$], [Ὲ], [$grave(epsilon)$], [ὲ],
      [--], [--], [$grave(epsilon.alt)$], [ϵ̀],
      [--], [--], [$grave(epsilon.alt.rev)$], [϶̀],
      [--], [--], [$grave(epsilon.rev)$], [϶̀],
      [--], [--], [$grave(epsilon.rev.alt)$], [϶̀],
      [$grave(Eta)$], [Ὴ], [$grave(eta)$], [ὴ],
      [$grave(Gamma)$], [Γ̀], [$grave(gamma)$], [γ̀],
      [$grave(Iota)$], [Ὶ], [$grave(iota)$], [ὶ],
      [--], [--], [$grave(iota.inv)$], [℩̀],
      [$grave(Kappa)$], [Κ̀], [$grave(kappa)$], [κ̀],
      [--], [--], [$grave(kappa.alt)$], [ϰ̀],
      [$grave(Lambda)$], [Λ̀], [$grave(lambda)$], [λ̀],
      [$grave(Mu)$], [Μ̀], [$grave(mu)$], [μ̀],
      [$grave(Nu)$], [Ν̀], [$grave(nu)$], [ν̀],
      [$grave(Omega)$], [Ὼ], [$grave(omega)$], [ὼ],
      [--], [--], [$grave(Omega.inv)$], [℧̀],
      [$grave(Omicron)$], [Ὸ], [$grave(omicron)$], [ὸ],
      [$grave(Phi)$], [Φ̀], [$grave(phi)$], [φ̀],
      [--], [--], [$grave(phi.alt)$], [ϕ̀],
      [$grave(Pi)$], [Π̀], [$grave(pi)$], [π̀],
      [--], [--], [$grave(pi.alt)$], [ϖ̀],
      [$grave(Psi)$], [Ψ̀], [$grave(psi)$], [ψ̀],
      [$grave(Rho)$], [Ρ̀], [$grave(rho)$], [ρ̀],
      [--], [--], [$grave(rho.alt)$], [ϱ̀],
      [$grave(Sigma)$], [Σ̀], [$grave(sigma)$], [σ̀],
      [--], [--], [$grave(sigma.alt)$], [ς̀],
      [$grave(Tau)$], [Τ̀], [$grave(tau)$], [τ̀],
      [$grave(Theta)$], [Θ̀], [$grave(theta)$], [θ̀],
      [--], [--], [$grave(theta.alt)$], [ϑ̀],
      [--], [--], [$grave(Theta.alt)$], [ϴ̀],
      [$grave(Upsilon)$], [Ὺ], [$grave(upsilon)$], [ὺ],
      [$grave(Xi)$], [Ξ̀], [$grave(xi)$], [ξ̀],
      [$grave(Zeta)$], [Ζ̀], [$grave(zeta)$], [ζ̀],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$grave(0)$], [0̀],
      [$grave(1)$], [1̀],
      [$grave(2)$], [2̀],
      [$grave(3)$], [3̀],
      [$grave(4)$], [4̀],
      [$grave(5)$], [5̀],
      [$grave(6)$], [6̀],
      [$grave(7)$], [7̀],
      [$grave(8)$], [8̀],
      [$grave(9)$], [9̀],
    )
  ],
)

#pagebreak()

= harpoon

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$harpoon(A)$], [A⃑], [$harpoon(a)$], [a⃑],
      [$harpoon(B)$], [B⃑], [$harpoon(b)$], [b⃑],
      [$harpoon(C)$], [C⃑], [$harpoon(c)$], [c⃑],
      [$harpoon(D)$], [D⃑], [$harpoon(d)$], [d⃑],
      [$harpoon(E)$], [E⃑], [$harpoon(e)$], [e⃑],
      [$harpoon(F)$], [F⃑], [$harpoon(f)$], [f⃑],
      [$harpoon(G)$], [G⃑], [$harpoon(g)$], [g⃑],
      [$harpoon(H)$], [H⃑], [$harpoon(h)$], [h⃑],
      [$harpoon(I)$], [I⃑], [$harpoon(i)$], [i⃑],
      [$harpoon(J)$], [J⃑], [$harpoon(j)$], [j⃑],
      [$harpoon(K)$], [K⃑], [$harpoon(k)$], [k⃑],
      [$harpoon(L)$], [L⃑], [$harpoon(l)$], [l⃑],
      [$harpoon(M)$], [M⃑], [$harpoon(m)$], [m⃑],
      [$harpoon(N)$], [N⃑], [$harpoon(n)$], [n⃑],
      [$harpoon(O)$], [O⃑], [$harpoon(o)$], [o⃑],
      [$harpoon(P)$], [P⃑], [$harpoon(p)$], [p⃑],
      [$harpoon(Q)$], [Q⃑], [$harpoon(q)$], [q⃑],
      [$harpoon(R)$], [R⃑], [$harpoon(r)$], [r⃑],
      [$harpoon(S)$], [S⃑], [$harpoon(s)$], [s⃑],
      [$harpoon(T)$], [T⃑], [$harpoon(t)$], [t⃑],
      [$harpoon(U)$], [U⃑], [$harpoon(u)$], [u⃑],
      [$harpoon(V)$], [V⃑], [$harpoon(v)$], [v⃑],
      [$harpoon(W)$], [W⃑], [$harpoon(w)$], [w⃑],
      [$harpoon(X)$], [X⃑], [$harpoon(x)$], [x⃑],
      [$harpoon(Y)$], [Y⃑], [$harpoon(y)$], [y⃑],
      [$harpoon(Z)$], [Z⃑], [$harpoon(z)$], [z⃑],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$harpoon(Alpha)$], [Α⃑], [$harpoon(alpha)$], [α⃑],
      [$harpoon(Beta)$], [Β⃑], [$harpoon(beta)$], [β⃑],
      [--], [--], [$harpoon(beta.alt)$], [ϐ⃑],
      [$harpoon(Chi)$], [Χ⃑], [$harpoon(chi)$], [χ⃑],
      [$harpoon(Delta)$], [Δ⃑], [$harpoon(delta)$], [δ⃑],
      [$harpoon(Digamma)$], [Ϝ⃑], [$harpoon(digamma)$], [ϝ⃑],
      [$harpoon(Epsilon)$], [Ε⃑], [$harpoon(epsilon)$], [ε⃑],
      [--], [--], [$harpoon(epsilon.alt)$], [ϵ⃑],
      [--], [--], [$harpoon(epsilon.alt.rev)$], [϶⃑],
      [--], [--], [$harpoon(epsilon.rev)$], [϶⃑],
      [--], [--], [$harpoon(epsilon.rev.alt)$], [϶⃑],
      [$harpoon(Eta)$], [Η⃑], [$harpoon(eta)$], [η⃑],
      [$harpoon(Gamma)$], [Γ⃑], [$harpoon(gamma)$], [γ⃑],
      [$harpoon(Iota)$], [Ι⃑], [$harpoon(iota)$], [ι⃑],
      [--], [--], [$harpoon(iota.inv)$], [℩⃑],
      [$harpoon(Kappa)$], [Κ⃑], [$harpoon(kappa)$], [κ⃑],
      [--], [--], [$harpoon(kappa.alt)$], [ϰ⃑],
      [$harpoon(Lambda)$], [Λ⃑], [$harpoon(lambda)$], [λ⃑],
      [$harpoon(Mu)$], [Μ⃑], [$harpoon(mu)$], [μ⃑],
      [$harpoon(Nu)$], [Ν⃑], [$harpoon(nu)$], [ν⃑],
      [$harpoon(Omega)$], [Ω⃑], [$harpoon(omega)$], [ω⃑],
      [--], [--], [$harpoon(Omega.inv)$], [℧⃑],
      [$harpoon(Omicron)$], [Ο⃑], [$harpoon(omicron)$], [ο⃑],
      [$harpoon(Phi)$], [Φ⃑], [$harpoon(phi)$], [φ⃑],
      [--], [--], [$harpoon(phi.alt)$], [ϕ⃑],
      [$harpoon(Pi)$], [Π⃑], [$harpoon(pi)$], [π⃑],
      [--], [--], [$harpoon(pi.alt)$], [ϖ⃑],
      [$harpoon(Psi)$], [Ψ⃑], [$harpoon(psi)$], [ψ⃑],
      [$harpoon(Rho)$], [Ρ⃑], [$harpoon(rho)$], [ρ⃑],
      [--], [--], [$harpoon(rho.alt)$], [ϱ⃑],
      [$harpoon(Sigma)$], [Σ⃑], [$harpoon(sigma)$], [σ⃑],
      [--], [--], [$harpoon(sigma.alt)$], [ς⃑],
      [$harpoon(Tau)$], [Τ⃑], [$harpoon(tau)$], [τ⃑],
      [$harpoon(Theta)$], [Θ⃑], [$harpoon(theta)$], [θ⃑],
      [--], [--], [$harpoon(theta.alt)$], [ϑ⃑],
      [--], [--], [$harpoon(Theta.alt)$], [ϴ⃑],
      [$harpoon(Upsilon)$], [Υ⃑], [$harpoon(upsilon)$], [υ⃑],
      [$harpoon(Xi)$], [Ξ⃑], [$harpoon(xi)$], [ξ⃑],
      [$harpoon(Zeta)$], [Ζ⃑], [$harpoon(zeta)$], [ζ⃑],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$harpoon(0)$], [0⃑],
      [$harpoon(1)$], [1⃑],
      [$harpoon(2)$], [2⃑],
      [$harpoon(3)$], [3⃑],
      [$harpoon(4)$], [4⃑],
      [$harpoon(5)$], [5⃑],
      [$harpoon(6)$], [6⃑],
      [$harpoon(7)$], [7⃑],
      [$harpoon(8)$], [8⃑],
      [$harpoon(9)$], [9⃑],
    )
  ],
)

#pagebreak()

= harpoon.lt

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$harpoon.lt(A)$], [A⃐], [$harpoon.lt(a)$], [a⃐],
      [$harpoon.lt(B)$], [B⃐], [$harpoon.lt(b)$], [b⃐],
      [$harpoon.lt(C)$], [C⃐], [$harpoon.lt(c)$], [c⃐],
      [$harpoon.lt(D)$], [D⃐], [$harpoon.lt(d)$], [d⃐],
      [$harpoon.lt(E)$], [E⃐], [$harpoon.lt(e)$], [e⃐],
      [$harpoon.lt(F)$], [F⃐], [$harpoon.lt(f)$], [f⃐],
      [$harpoon.lt(G)$], [G⃐], [$harpoon.lt(g)$], [g⃐],
      [$harpoon.lt(H)$], [H⃐], [$harpoon.lt(h)$], [h⃐],
      [$harpoon.lt(I)$], [I⃐], [$harpoon.lt(i)$], [i⃐],
      [$harpoon.lt(J)$], [J⃐], [$harpoon.lt(j)$], [j⃐],
      [$harpoon.lt(K)$], [K⃐], [$harpoon.lt(k)$], [k⃐],
      [$harpoon.lt(L)$], [L⃐], [$harpoon.lt(l)$], [l⃐],
      [$harpoon.lt(M)$], [M⃐], [$harpoon.lt(m)$], [m⃐],
      [$harpoon.lt(N)$], [N⃐], [$harpoon.lt(n)$], [n⃐],
      [$harpoon.lt(O)$], [O⃐], [$harpoon.lt(o)$], [o⃐],
      [$harpoon.lt(P)$], [P⃐], [$harpoon.lt(p)$], [p⃐],
      [$harpoon.lt(Q)$], [Q⃐], [$harpoon.lt(q)$], [q⃐],
      [$harpoon.lt(R)$], [R⃐], [$harpoon.lt(r)$], [r⃐],
      [$harpoon.lt(S)$], [S⃐], [$harpoon.lt(s)$], [s⃐],
      [$harpoon.lt(T)$], [T⃐], [$harpoon.lt(t)$], [t⃐],
      [$harpoon.lt(U)$], [U⃐], [$harpoon.lt(u)$], [u⃐],
      [$harpoon.lt(V)$], [V⃐], [$harpoon.lt(v)$], [v⃐],
      [$harpoon.lt(W)$], [W⃐], [$harpoon.lt(w)$], [w⃐],
      [$harpoon.lt(X)$], [X⃐], [$harpoon.lt(x)$], [x⃐],
      [$harpoon.lt(Y)$], [Y⃐], [$harpoon.lt(y)$], [y⃐],
      [$harpoon.lt(Z)$], [Z⃐], [$harpoon.lt(z)$], [z⃐],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$harpoon.lt(Alpha)$], [Α⃐], [$harpoon.lt(alpha)$], [α⃐],
      [$harpoon.lt(Beta)$], [Β⃐], [$harpoon.lt(beta)$], [β⃐],
      [--], [--], [$harpoon.lt(beta.alt)$], [ϐ⃐],
      [$harpoon.lt(Chi)$], [Χ⃐], [$harpoon.lt(chi)$], [χ⃐],
      [$harpoon.lt(Delta)$], [Δ⃐], [$harpoon.lt(delta)$], [δ⃐],
      [$harpoon.lt(Digamma)$], [Ϝ⃐], [$harpoon.lt(digamma)$], [ϝ⃐],
      [$harpoon.lt(Epsilon)$], [Ε⃐], [$harpoon.lt(epsilon)$], [ε⃐],
      [--], [--], [$harpoon.lt(epsilon.alt)$], [ϵ⃐],
      [--], [--], [$harpoon.lt(epsilon.alt.rev)$], [϶⃐],
      [--], [--], [$harpoon.lt(epsilon.rev)$], [϶⃐],
      [--], [--], [$harpoon.lt(epsilon.rev.alt)$], [϶⃐],
      [$harpoon.lt(Eta)$], [Η⃐], [$harpoon.lt(eta)$], [η⃐],
      [$harpoon.lt(Gamma)$], [Γ⃐], [$harpoon.lt(gamma)$], [γ⃐],
      [$harpoon.lt(Iota)$], [Ι⃐], [$harpoon.lt(iota)$], [ι⃐],
      [--], [--], [$harpoon.lt(iota.inv)$], [℩⃐],
      [$harpoon.lt(Kappa)$], [Κ⃐], [$harpoon.lt(kappa)$], [κ⃐],
      [--], [--], [$harpoon.lt(kappa.alt)$], [ϰ⃐],
      [$harpoon.lt(Lambda)$], [Λ⃐], [$harpoon.lt(lambda)$], [λ⃐],
      [$harpoon.lt(Mu)$], [Μ⃐], [$harpoon.lt(mu)$], [μ⃐],
      [$harpoon.lt(Nu)$], [Ν⃐], [$harpoon.lt(nu)$], [ν⃐],
      [$harpoon.lt(Omega)$], [Ω⃐], [$harpoon.lt(omega)$], [ω⃐],
      [--], [--], [$harpoon.lt(Omega.inv)$], [℧⃐],
      [$harpoon.lt(Omicron)$], [Ο⃐], [$harpoon.lt(omicron)$], [ο⃐],
      [$harpoon.lt(Phi)$], [Φ⃐], [$harpoon.lt(phi)$], [φ⃐],
      [--], [--], [$harpoon.lt(phi.alt)$], [ϕ⃐],
      [$harpoon.lt(Pi)$], [Π⃐], [$harpoon.lt(pi)$], [π⃐],
      [--], [--], [$harpoon.lt(pi.alt)$], [ϖ⃐],
      [$harpoon.lt(Psi)$], [Ψ⃐], [$harpoon.lt(psi)$], [ψ⃐],
      [$harpoon.lt(Rho)$], [Ρ⃐], [$harpoon.lt(rho)$], [ρ⃐],
      [--], [--], [$harpoon.lt(rho.alt)$], [ϱ⃐],
      [$harpoon.lt(Sigma)$], [Σ⃐], [$harpoon.lt(sigma)$], [σ⃐],
      [--], [--], [$harpoon.lt(sigma.alt)$], [ς⃐],
      [$harpoon.lt(Tau)$], [Τ⃐], [$harpoon.lt(tau)$], [τ⃐],
      [$harpoon.lt(Theta)$], [Θ⃐], [$harpoon.lt(theta)$], [θ⃐],
      [--], [--], [$harpoon.lt(theta.alt)$], [ϑ⃐],
      [--], [--], [$harpoon.lt(Theta.alt)$], [ϴ⃐],
      [$harpoon.lt(Upsilon)$], [Υ⃐], [$harpoon.lt(upsilon)$], [υ⃐],
      [$harpoon.lt(Xi)$], [Ξ⃐], [$harpoon.lt(xi)$], [ξ⃐],
      [$harpoon.lt(Zeta)$], [Ζ⃐], [$harpoon.lt(zeta)$], [ζ⃐],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$harpoon.lt(0)$], [0⃐],
      [$harpoon.lt(1)$], [1⃐],
      [$harpoon.lt(2)$], [2⃐],
      [$harpoon.lt(3)$], [3⃐],
      [$harpoon.lt(4)$], [4⃐],
      [$harpoon.lt(5)$], [5⃐],
      [$harpoon.lt(6)$], [6⃐],
      [$harpoon.lt(7)$], [7⃐],
      [$harpoon.lt(8)$], [8⃐],
      [$harpoon.lt(9)$], [9⃐],
    )
  ],
)

#pagebreak()

= hat

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$hat(A)$], [Â], [$hat(a)$], [â],
      [$hat(B)$], [B̂], [$hat(b)$], [b̂],
      [$hat(C)$], [Ĉ], [$hat(c)$], [ĉ],
      [$hat(D)$], [D̂], [$hat(d)$], [d̂],
      [$hat(E)$], [Ê], [$hat(e)$], [ê],
      [$hat(F)$], [F̂], [$hat(f)$], [f̂],
      [$hat(G)$], [Ĝ], [$hat(g)$], [ĝ],
      [$hat(H)$], [Ĥ], [$hat(h)$], [ĥ],
      [$hat(I)$], [Î], [$hat(i)$], [î],
      [$hat(J)$], [Ĵ], [$hat(j)$], [ĵ],
      [$hat(K)$], [K̂], [$hat(k)$], [k̂],
      [$hat(L)$], [L̂], [$hat(l)$], [l̂],
      [$hat(M)$], [M̂], [$hat(m)$], [m̂],
      [$hat(N)$], [N̂], [$hat(n)$], [n̂],
      [$hat(O)$], [Ô], [$hat(o)$], [ô],
      [$hat(P)$], [P̂], [$hat(p)$], [p̂],
      [$hat(Q)$], [Q̂], [$hat(q)$], [q̂],
      [$hat(R)$], [R̂], [$hat(r)$], [r̂],
      [$hat(S)$], [Ŝ], [$hat(s)$], [ŝ],
      [$hat(T)$], [T̂], [$hat(t)$], [t̂],
      [$hat(U)$], [Û], [$hat(u)$], [û],
      [$hat(V)$], [V̂], [$hat(v)$], [v̂],
      [$hat(W)$], [Ŵ], [$hat(w)$], [ŵ],
      [$hat(X)$], [X̂], [$hat(x)$], [x̂],
      [$hat(Y)$], [Ŷ], [$hat(y)$], [ŷ],
      [$hat(Z)$], [Ẑ], [$hat(z)$], [ẑ],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$hat(Alpha)$], [Α̂], [$hat(alpha)$], [α̂],
      [$hat(Beta)$], [Β̂], [$hat(beta)$], [β̂],
      [--], [--], [$hat(beta.alt)$], [ϐ̂],
      [$hat(Chi)$], [Χ̂], [$hat(chi)$], [χ̂],
      [$hat(Delta)$], [Δ̂], [$hat(delta)$], [δ̂],
      [$hat(Digamma)$], [Ϝ̂], [$hat(digamma)$], [ϝ̂],
      [$hat(Epsilon)$], [Ε̂], [$hat(epsilon)$], [ε̂],
      [--], [--], [$hat(epsilon.alt)$], [ϵ̂],
      [--], [--], [$hat(epsilon.alt.rev)$], [϶̂],
      [--], [--], [$hat(epsilon.rev)$], [϶̂],
      [--], [--], [$hat(epsilon.rev.alt)$], [϶̂],
      [$hat(Eta)$], [Η̂], [$hat(eta)$], [η̂],
      [$hat(Gamma)$], [Γ̂], [$hat(gamma)$], [γ̂],
      [$hat(Iota)$], [Ι̂], [$hat(iota)$], [ι̂],
      [--], [--], [$hat(iota.inv)$], [℩̂],
      [$hat(Kappa)$], [Κ̂], [$hat(kappa)$], [κ̂],
      [--], [--], [$hat(kappa.alt)$], [ϰ̂],
      [$hat(Lambda)$], [Λ̂], [$hat(lambda)$], [λ̂],
      [$hat(Mu)$], [Μ̂], [$hat(mu)$], [μ̂],
      [$hat(Nu)$], [Ν̂], [$hat(nu)$], [ν̂],
      [$hat(Omega)$], [Ω̂], [$hat(omega)$], [ω̂],
      [--], [--], [$hat(Omega.inv)$], [℧̂],
      [$hat(Omicron)$], [Ο̂], [$hat(omicron)$], [ο̂],
      [$hat(Phi)$], [Φ̂], [$hat(phi)$], [φ̂],
      [--], [--], [$hat(phi.alt)$], [ϕ̂],
      [$hat(Pi)$], [Π̂], [$hat(pi)$], [π̂],
      [--], [--], [$hat(pi.alt)$], [ϖ̂],
      [$hat(Psi)$], [Ψ̂], [$hat(psi)$], [ψ̂],
      [$hat(Rho)$], [Ρ̂], [$hat(rho)$], [ρ̂],
      [--], [--], [$hat(rho.alt)$], [ϱ̂],
      [$hat(Sigma)$], [Σ̂], [$hat(sigma)$], [σ̂],
      [--], [--], [$hat(sigma.alt)$], [ς̂],
      [$hat(Tau)$], [Τ̂], [$hat(tau)$], [τ̂],
      [$hat(Theta)$], [Θ̂], [$hat(theta)$], [θ̂],
      [--], [--], [$hat(theta.alt)$], [ϑ̂],
      [--], [--], [$hat(Theta.alt)$], [ϴ̂],
      [$hat(Upsilon)$], [Υ̂], [$hat(upsilon)$], [υ̂],
      [$hat(Xi)$], [Ξ̂], [$hat(xi)$], [ξ̂],
      [$hat(Zeta)$], [Ζ̂], [$hat(zeta)$], [ζ̂],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$hat(0)$], [0̂],
      [$hat(1)$], [1̂],
      [$hat(2)$], [2̂],
      [$hat(3)$], [3̂],
      [$hat(4)$], [4̂],
      [$hat(5)$], [5̂],
      [$hat(6)$], [6̂],
      [$hat(7)$], [7̂],
      [$hat(8)$], [8̂],
      [$hat(9)$], [9̂],
    )
  ],
)

#pagebreak()

= macron

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$macron(A)$], [Ā], [$macron(a)$], [ā],
      [$macron(B)$], [B̄], [$macron(b)$], [b̄],
      [$macron(C)$], [C̄], [$macron(c)$], [c̄],
      [$macron(D)$], [D̄], [$macron(d)$], [d̄],
      [$macron(E)$], [Ē], [$macron(e)$], [ē],
      [$macron(F)$], [F̄], [$macron(f)$], [f̄],
      [$macron(G)$], [Ḡ], [$macron(g)$], [ḡ],
      [$macron(H)$], [H̄], [$macron(h)$], [h̄],
      [$macron(I)$], [Ī], [$macron(i)$], [ī],
      [$macron(J)$], [J̄], [$macron(j)$], [j̄],
      [$macron(K)$], [K̄], [$macron(k)$], [k̄],
      [$macron(L)$], [L̄], [$macron(l)$], [l̄],
      [$macron(M)$], [M̄], [$macron(m)$], [m̄],
      [$macron(N)$], [N̄], [$macron(n)$], [n̄],
      [$macron(O)$], [Ō], [$macron(o)$], [ō],
      [$macron(P)$], [P̄], [$macron(p)$], [p̄],
      [$macron(Q)$], [Q̄], [$macron(q)$], [q̄],
      [$macron(R)$], [R̄], [$macron(r)$], [r̄],
      [$macron(S)$], [S̄], [$macron(s)$], [s̄],
      [$macron(T)$], [T̄], [$macron(t)$], [t̄],
      [$macron(U)$], [Ū], [$macron(u)$], [ū],
      [$macron(V)$], [V̄], [$macron(v)$], [v̄],
      [$macron(W)$], [W̄], [$macron(w)$], [w̄],
      [$macron(X)$], [X̄], [$macron(x)$], [x̄],
      [$macron(Y)$], [Ȳ], [$macron(y)$], [ȳ],
      [$macron(Z)$], [Z̄], [$macron(z)$], [z̄],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$macron(Alpha)$], [Ᾱ], [$macron(alpha)$], [ᾱ],
      [$macron(Beta)$], [Β̄], [$macron(beta)$], [β̄],
      [--], [--], [$macron(beta.alt)$], [ϐ̄],
      [$macron(Chi)$], [Χ̄], [$macron(chi)$], [χ̄],
      [$macron(Delta)$], [Δ̄], [$macron(delta)$], [δ̄],
      [$macron(Digamma)$], [Ϝ̄], [$macron(digamma)$], [ϝ̄],
      [$macron(Epsilon)$], [Ε̄], [$macron(epsilon)$], [ε̄],
      [--], [--], [$macron(epsilon.alt)$], [ϵ̄],
      [--], [--], [$macron(epsilon.alt.rev)$], [϶̄],
      [--], [--], [$macron(epsilon.rev)$], [϶̄],
      [--], [--], [$macron(epsilon.rev.alt)$], [϶̄],
      [$macron(Eta)$], [Η̄], [$macron(eta)$], [η̄],
      [$macron(Gamma)$], [Γ̄], [$macron(gamma)$], [γ̄],
      [$macron(Iota)$], [Ῑ], [$macron(iota)$], [ῑ],
      [--], [--], [$macron(iota.inv)$], [℩̄],
      [$macron(Kappa)$], [Κ̄], [$macron(kappa)$], [κ̄],
      [--], [--], [$macron(kappa.alt)$], [ϰ̄],
      [$macron(Lambda)$], [Λ̄], [$macron(lambda)$], [λ̄],
      [$macron(Mu)$], [Μ̄], [$macron(mu)$], [μ̄],
      [$macron(Nu)$], [Ν̄], [$macron(nu)$], [ν̄],
      [$macron(Omega)$], [Ω̄], [$macron(omega)$], [ω̄],
      [--], [--], [$macron(Omega.inv)$], [℧̄],
      [$macron(Omicron)$], [Ο̄], [$macron(omicron)$], [ο̄],
      [$macron(Phi)$], [Φ̄], [$macron(phi)$], [φ̄],
      [--], [--], [$macron(phi.alt)$], [ϕ̄],
      [$macron(Pi)$], [Π̄], [$macron(pi)$], [π̄],
      [--], [--], [$macron(pi.alt)$], [ϖ̄],
      [$macron(Psi)$], [Ψ̄], [$macron(psi)$], [ψ̄],
      [$macron(Rho)$], [Ρ̄], [$macron(rho)$], [ρ̄],
      [--], [--], [$macron(rho.alt)$], [ϱ̄],
      [$macron(Sigma)$], [Σ̄], [$macron(sigma)$], [σ̄],
      [--], [--], [$macron(sigma.alt)$], [ς̄],
      [$macron(Tau)$], [Τ̄], [$macron(tau)$], [τ̄],
      [$macron(Theta)$], [Θ̄], [$macron(theta)$], [θ̄],
      [--], [--], [$macron(theta.alt)$], [ϑ̄],
      [--], [--], [$macron(Theta.alt)$], [ϴ̄],
      [$macron(Upsilon)$], [Ῡ], [$macron(upsilon)$], [ῡ],
      [$macron(Xi)$], [Ξ̄], [$macron(xi)$], [ξ̄],
      [$macron(Zeta)$], [Ζ̄], [$macron(zeta)$], [ζ̄],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$macron(0)$], [0̄],
      [$macron(1)$], [1̄],
      [$macron(2)$], [2̄],
      [$macron(3)$], [3̄],
      [$macron(4)$], [4̄],
      [$macron(5)$], [5̄],
      [$macron(6)$], [6̄],
      [$macron(7)$], [7̄],
      [$macron(8)$], [8̄],
      [$macron(9)$], [9̄],
    )
  ],
)

#pagebreak()

= overline

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$overline(A)$], [A̅], [$overline(a)$], [a̅],
      [$overline(B)$], [B̅], [$overline(b)$], [b̅],
      [$overline(C)$], [C̅], [$overline(c)$], [c̅],
      [$overline(D)$], [D̅], [$overline(d)$], [d̅],
      [$overline(E)$], [E̅], [$overline(e)$], [e̅],
      [$overline(F)$], [F̅], [$overline(f)$], [f̅],
      [$overline(G)$], [G̅], [$overline(g)$], [g̅],
      [$overline(H)$], [H̅], [$overline(h)$], [h̅],
      [$overline(I)$], [I̅], [$overline(i)$], [i̅],
      [$overline(J)$], [J̅], [$overline(j)$], [j̅],
      [$overline(K)$], [K̅], [$overline(k)$], [k̅],
      [$overline(L)$], [L̅], [$overline(l)$], [l̅],
      [$overline(M)$], [M̅], [$overline(m)$], [m̅],
      [$overline(N)$], [N̅], [$overline(n)$], [n̅],
      [$overline(O)$], [O̅], [$overline(o)$], [o̅],
      [$overline(P)$], [P̅], [$overline(p)$], [p̅],
      [$overline(Q)$], [Q̅], [$overline(q)$], [q̅],
      [$overline(R)$], [R̅], [$overline(r)$], [r̅],
      [$overline(S)$], [S̅], [$overline(s)$], [s̅],
      [$overline(T)$], [T̅], [$overline(t)$], [t̅],
      [$overline(U)$], [U̅], [$overline(u)$], [u̅],
      [$overline(V)$], [V̅], [$overline(v)$], [v̅],
      [$overline(W)$], [W̅], [$overline(w)$], [w̅],
      [$overline(X)$], [X̅], [$overline(x)$], [x̅],
      [$overline(Y)$], [Y̅], [$overline(y)$], [y̅],
      [$overline(Z)$], [Z̅], [$overline(z)$], [z̅],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$overline(Alpha)$], [Α̅], [$overline(alpha)$], [α̅],
      [$overline(Beta)$], [Β̅], [$overline(beta)$], [β̅],
      [--], [--], [$overline(beta.alt)$], [ϐ̅],
      [$overline(Chi)$], [Χ̅], [$overline(chi)$], [χ̅],
      [$overline(Delta)$], [Δ̅], [$overline(delta)$], [δ̅],
      [$overline(Digamma)$], [Ϝ̅], [$overline(digamma)$], [ϝ̅],
      [$overline(Epsilon)$], [Ε̅], [$overline(epsilon)$], [ε̅],
      [--], [--], [$overline(epsilon.alt)$], [ϵ̅],
      [--], [--], [$overline(epsilon.alt.rev)$], [϶̅],
      [--], [--], [$overline(epsilon.rev)$], [϶̅],
      [--], [--], [$overline(epsilon.rev.alt)$], [϶̅],
      [$overline(Eta)$], [Η̅], [$overline(eta)$], [η̅],
      [$overline(Gamma)$], [Γ̅], [$overline(gamma)$], [γ̅],
      [$overline(Iota)$], [Ι̅], [$overline(iota)$], [ι̅],
      [--], [--], [$overline(iota.inv)$], [℩̅],
      [$overline(Kappa)$], [Κ̅], [$overline(kappa)$], [κ̅],
      [--], [--], [$overline(kappa.alt)$], [ϰ̅],
      [$overline(Lambda)$], [Λ̅], [$overline(lambda)$], [λ̅],
      [$overline(Mu)$], [Μ̅], [$overline(mu)$], [μ̅],
      [$overline(Nu)$], [Ν̅], [$overline(nu)$], [ν̅],
      [$overline(Omega)$], [Ω̅], [$overline(omega)$], [ω̅],
      [--], [--], [$overline(Omega.inv)$], [℧̅],
      [$overline(Omicron)$], [Ο̅], [$overline(omicron)$], [ο̅],
      [$overline(Phi)$], [Φ̅], [$overline(phi)$], [φ̅],
      [--], [--], [$overline(phi.alt)$], [ϕ̅],
      [$overline(Pi)$], [Π̅], [$overline(pi)$], [π̅],
      [--], [--], [$overline(pi.alt)$], [ϖ̅],
      [$overline(Psi)$], [Ψ̅], [$overline(psi)$], [ψ̅],
      [$overline(Rho)$], [Ρ̅], [$overline(rho)$], [ρ̅],
      [--], [--], [$overline(rho.alt)$], [ϱ̅],
      [$overline(Sigma)$], [Σ̅], [$overline(sigma)$], [σ̅],
      [--], [--], [$overline(sigma.alt)$], [ς̅],
      [$overline(Tau)$], [Τ̅], [$overline(tau)$], [τ̅],
      [$overline(Theta)$], [Θ̅], [$overline(theta)$], [θ̅],
      [--], [--], [$overline(theta.alt)$], [ϑ̅],
      [--], [--], [$overline(Theta.alt)$], [ϴ̅],
      [$overline(Upsilon)$], [Υ̅], [$overline(upsilon)$], [υ̅],
      [$overline(Xi)$], [Ξ̅], [$overline(xi)$], [ξ̅],
      [$overline(Zeta)$], [Ζ̅], [$overline(zeta)$], [ζ̅],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$overline(0)$], [0̅],
      [$overline(1)$], [1̅],
      [$overline(2)$], [2̅],
      [$overline(3)$], [3̅],
      [$overline(4)$], [4̅],
      [$overline(5)$], [5̅],
      [$overline(6)$], [6̅],
      [$overline(7)$], [7̅],
      [$overline(8)$], [8̅],
      [$overline(9)$], [9̅],
    )
  ],
)

#pagebreak()

= tilde

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$tilde(A)$], [Ã], [$tilde(a)$], [ã],
      [$tilde(B)$], [B̃], [$tilde(b)$], [b̃],
      [$tilde(C)$], [C̃], [$tilde(c)$], [c̃],
      [$tilde(D)$], [D̃], [$tilde(d)$], [d̃],
      [$tilde(E)$], [Ẽ], [$tilde(e)$], [ẽ],
      [$tilde(F)$], [F̃], [$tilde(f)$], [f̃],
      [$tilde(G)$], [G̃], [$tilde(g)$], [g̃],
      [$tilde(H)$], [H̃], [$tilde(h)$], [h̃],
      [$tilde(I)$], [Ĩ], [$tilde(i)$], [ĩ],
      [$tilde(J)$], [J̃], [$tilde(j)$], [j̃],
      [$tilde(K)$], [K̃], [$tilde(k)$], [k̃],
      [$tilde(L)$], [L̃], [$tilde(l)$], [l̃],
      [$tilde(M)$], [M̃], [$tilde(m)$], [m̃],
      [$tilde(N)$], [Ñ], [$tilde(n)$], [ñ],
      [$tilde(O)$], [Õ], [$tilde(o)$], [õ],
      [$tilde(P)$], [P̃], [$tilde(p)$], [p̃],
      [$tilde(Q)$], [Q̃], [$tilde(q)$], [q̃],
      [$tilde(R)$], [R̃], [$tilde(r)$], [r̃],
      [$tilde(S)$], [S̃], [$tilde(s)$], [s̃],
      [$tilde(T)$], [T̃], [$tilde(t)$], [t̃],
      [$tilde(U)$], [Ũ], [$tilde(u)$], [ũ],
      [$tilde(V)$], [Ṽ], [$tilde(v)$], [ṽ],
      [$tilde(W)$], [W̃], [$tilde(w)$], [w̃],
      [$tilde(X)$], [X̃], [$tilde(x)$], [x̃],
      [$tilde(Y)$], [Ỹ], [$tilde(y)$], [ỹ],
      [$tilde(Z)$], [Z̃], [$tilde(z)$], [z̃],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*], [*Render*], [*Unicode*],
      [$tilde(Alpha)$], [Α̃], [$tilde(alpha)$], [α̃],
      [$tilde(Beta)$], [Β̃], [$tilde(beta)$], [β̃],
      [--], [--], [$tilde(beta.alt)$], [ϐ̃],
      [$tilde(Chi)$], [Χ̃], [$tilde(chi)$], [χ̃],
      [$tilde(Delta)$], [Δ̃], [$tilde(delta)$], [δ̃],
      [$tilde(Digamma)$], [Ϝ̃], [$tilde(digamma)$], [ϝ̃],
      [$tilde(Epsilon)$], [Ε̃], [$tilde(epsilon)$], [ε̃],
      [--], [--], [$tilde(epsilon.alt)$], [ϵ̃],
      [--], [--], [$tilde(epsilon.alt.rev)$], [϶̃],
      [--], [--], [$tilde(epsilon.rev)$], [϶̃],
      [--], [--], [$tilde(epsilon.rev.alt)$], [϶̃],
      [$tilde(Eta)$], [Η̃], [$tilde(eta)$], [η̃],
      [$tilde(Gamma)$], [Γ̃], [$tilde(gamma)$], [γ̃],
      [$tilde(Iota)$], [Ι̃], [$tilde(iota)$], [ι̃],
      [--], [--], [$tilde(iota.inv)$], [℩̃],
      [$tilde(Kappa)$], [Κ̃], [$tilde(kappa)$], [κ̃],
      [--], [--], [$tilde(kappa.alt)$], [ϰ̃],
      [$tilde(Lambda)$], [Λ̃], [$tilde(lambda)$], [λ̃],
      [$tilde(Mu)$], [Μ̃], [$tilde(mu)$], [μ̃],
      [$tilde(Nu)$], [Ν̃], [$tilde(nu)$], [ν̃],
      [$tilde(Omega)$], [Ω̃], [$tilde(omega)$], [ω̃],
      [--], [--], [$tilde(Omega.inv)$], [℧̃],
      [$tilde(Omicron)$], [Ο̃], [$tilde(omicron)$], [ο̃],
      [$tilde(Phi)$], [Φ̃], [$tilde(phi)$], [φ̃],
      [--], [--], [$tilde(phi.alt)$], [ϕ̃],
      [$tilde(Pi)$], [Π̃], [$tilde(pi)$], [π̃],
      [--], [--], [$tilde(pi.alt)$], [ϖ̃],
      [$tilde(Psi)$], [Ψ̃], [$tilde(psi)$], [ψ̃],
      [$tilde(Rho)$], [Ρ̃], [$tilde(rho)$], [ρ̃],
      [--], [--], [$tilde(rho.alt)$], [ϱ̃],
      [$tilde(Sigma)$], [Σ̃], [$tilde(sigma)$], [σ̃],
      [--], [--], [$tilde(sigma.alt)$], [ς̃],
      [$tilde(Tau)$], [Τ̃], [$tilde(tau)$], [τ̃],
      [$tilde(Theta)$], [Θ̃], [$tilde(theta)$], [θ̃],
      [--], [--], [$tilde(theta.alt)$], [ϑ̃],
      [--], [--], [$tilde(Theta.alt)$], [ϴ̃],
      [$tilde(Upsilon)$], [Υ̃], [$tilde(upsilon)$], [υ̃],
      [$tilde(Xi)$], [Ξ̃], [$tilde(xi)$], [ξ̃],
      [$tilde(Zeta)$], [Ζ̃], [$tilde(zeta)$], [ζ̃],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Render*], [*Unicode*],
      [$tilde(0)$], [0̃],
      [$tilde(1)$], [1̃],
      [$tilde(2)$], [2̃],
      [$tilde(3)$], [3̃],
      [$tilde(4)$], [4̃],
      [$tilde(5)$], [5̃],
      [$tilde(6)$], [6̃],
      [$tilde(7)$], [7̃],
      [$tilde(8)$], [8̃],
      [$tilde(9)$], [9̃],
    )
  ],
)
