#set page(paper: "a4", margin: 1cm)
#set text(font: ("STIX", "STIX Two Text"))

= Blackboard Bold (bb)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$bb(A)$],       [𝔸],        [$bb(a)$],       [𝕒],
      [$bb(B)$],       [𝔹],        [$bb(b)$],       [𝕓],
      [$bb(C)$],       [ℂ],        [$bb(c)$],       [𝕔],
      [$bb(D)$],       [𝔻],        [$bb(d)$],       [𝕕],
      [$bb(E)$],       [𝔼],        [$bb(e)$],       [𝕖],
      [$bb(F)$],       [𝔽],        [$bb(f)$],       [𝕗],
      [$bb(G)$],       [𝔾],        [$bb(g)$],       [𝕘],
      [$bb(H)$],       [ℍ],        [$bb(h)$],       [𝕙],
      [$bb(I)$],       [𝕀],        [$bb(i)$],       [𝕚],
      [$bb(J)$],       [𝕁],        [$bb(j)$],       [𝕛],
      [$bb(K)$],       [𝕂],        [$bb(k)$],       [𝕜],
      [$bb(L)$],       [𝕃],        [$bb(l)$],       [𝕝],
      [$bb(M)$],       [𝕄],        [$bb(m)$],       [𝕞],
      [$bb(N)$],       [ℕ],        [$bb(n)$],       [𝕟],
      [$bb(O)$],       [𝕆],        [$bb(o)$],       [𝕠],
      [$bb(P)$],       [ℙ],        [$bb(p)$],       [𝕡],
      [$bb(Q)$],       [ℚ],        [$bb(q)$],       [𝕢],
      [$bb(R)$],       [ℝ],        [$bb(r)$],       [𝕣],
      [$bb(S)$],       [𝕊],        [$bb(s)$],       [𝕤],
      [$bb(T)$],       [𝕋],        [$bb(t)$],       [𝕥],
      [$bb(U)$],       [𝕌],        [$bb(u)$],       [𝕦],
      [$bb(V)$],       [𝕍],        [$bb(v)$],       [𝕧],
      [$bb(W)$],       [𝕎],        [$bb(w)$],       [𝕨],
      [$bb(X)$],       [𝕏],        [$bb(x)$],       [𝕩],
      [$bb(Y)$],       [𝕐],        [$bb(y)$],       [𝕪],
      [$bb(Z)$],       [ℤ],        [$bb(z)$],       [𝕫],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*],     [*Symbol*],
      [$bb(Alpha)$],   [$ Α $],        [$bb(alpha)$],       [$ 𝛼 $],
      [$bb(Beta)$],    [$ Β $],        [$bb(beta)$],        [$ 𝛽 $],
      [$bb(Gamma)$],   [$ ℾ $],        [$bb(gamma)$],       [$ ℽ $],
      [$bb(Delta)$],   [$ Δ $],        [$bb(delta)$],       [$ 𝛿 $],
      [$bb(Digamma)$], [$ Ϝ $],        [$bb(digamma)$],     [$ ϝ $],
      [$bb(Epsilon)$], [$ Ε $],        [$bb(epsilon)$],     [$ 𝜀 $],
      [$bb(Zeta)$],    [$ Ζ $],        [$bb(zeta)$],        [$ 𝜁 $],
      [$bb(Eta)$],     [$ Η $],        [$bb(eta)$],         [$ 𝜂 $],
      [$bb(Theta)$],   [$ Θ $],        [$bb(theta)$],       [$ 𝜃 $],
      [$bb(Iota)$],    [$ Ι $],        [$bb(iota)$],        [$ 𝜄 $],
      [$bb(Kappa)$],   [$ Κ $],        [$bb(kappa)$],       [$ 𝜅 $],
      [$bb(Lambda)$],  [$ Λ $],        [$bb(lambda)$],      [$ 𝜆 $],
      [$bb(Mu)$],      [$ Μ $],        [$bb(mu)$],          [$ 𝜇 $],
      [$bb(Nu)$],      [$ Ν $],        [$bb(nu)$],          [$ 𝜈 $],
      [$bb(Xi)$],      [$ Ξ $],        [$bb(xi)$],          [$ 𝜉 $],
      [$bb(Omicron)$], [$ Ο $],        [$bb(omicron)$],     [$ 𝜊 $],
      [$bb(Pi)$],      [$ ℿ $],        [$bb(pi)$],          [$ ℼ $],
      [$bb(Rho)$],     [$ Ρ $],        [$bb(rho)$],         [$ 𝜌 $],
      [$bb(Sigma)$],   [$ Σ $],        [$bb(sigma)$],       [$ 𝜎 $],
      [$bb(Tau)$],     [$ Τ $],        [$bb(tau)$],         [$ 𝜏 $],
      [$bb(Upsilon)$], [$ Υ $],        [$bb(upsilon)$],     [$ 𝜐 $],
      [$bb(Phi)$],     [$ Φ $],        [$bb(phi)$],         [$ 𝜑 $],
      [$bb(Chi)$],     [$ Χ $],        [$bb(chi)$],         [$ 𝜒 $],
      [$bb(Psi)$],     [$ Ψ $],        [$bb(psi)$],         [$ 𝜓 $],
      [$bb(Omega)$],   [$ Ω $],        [$bb(omega)$],       [$ 𝜔 $],
      [],              [],         [$bb(epsilon.alt)$], [$ 𝜖 $],
      [],              [],         [$bb(Theta.alt)$],   [$ ϴ $],
      [],              [],         [$bb(theta.alt)$],   [$ 𝜗 $],
      [],              [],         [$bb(kappa.alt)$],   [$ 𝜘 $],
      [],              [],         [$bb(pi.alt)$],      [$ 𝜛 $],
      [],              [],         [$bb(rho.alt)$],     [$ 𝜚 $],
      [],              [],         [$bb(sigma.alt)$],   [$ 𝜍 $],
      [],              [],         [$bb(phi.alt)$],     [$ 𝜙 $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$bb(0)$],  [𝟘],
      [$bb(1)$],  [𝟙],
      [$bb(2)$],  [𝟚],
      [$bb(3)$],  [𝟛],
      [$bb(4)$],  [𝟜],
      [$bb(5)$],  [𝟝],
      [$bb(6)$],  [𝟞],
      [$bb(7)$],  [𝟟],
      [$bb(8)$],  [𝟠],
      [$bb(9)$],  [𝟡],
    )
  ],
)

#pagebreak()

= Bold

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$bold(A)$],     [𝐀],        [$bold(a)$],     [𝐚],
      [$bold(B)$],     [𝐁],        [$bold(b)$],     [𝐛],
      [$bold(C)$],     [𝐂],        [$bold(c)$],     [𝐜],
      [$bold(D)$],     [𝐃],        [$bold(d)$],     [𝐝],
      [$bold(E)$],     [𝐄],        [$bold(e)$],     [𝐞],
      [$bold(F)$],     [𝐅],        [$bold(f)$],     [𝐟],
      [$bold(G)$],     [𝐆],        [$bold(g)$],     [𝐠],
      [$bold(H)$],     [𝐇],        [$bold(h)$],     [𝐡],
      [$bold(I)$],     [𝐈],        [$bold(i)$],     [𝐢],
      [$bold(J)$],     [𝐉],        [$bold(j)$],     [𝐣],
      [$bold(K)$],     [𝐊],        [$bold(k)$],     [𝐤],
      [$bold(L)$],     [𝐋],        [$bold(l)$],     [𝐥],
      [$bold(M)$],     [𝐌],        [$bold(m)$],     [𝐦],
      [$bold(N)$],     [𝐍],        [$bold(n)$],     [𝐧],
      [$bold(O)$],     [𝐎],        [$bold(o)$],     [𝐨],
      [$bold(P)$],     [𝐏],        [$bold(p)$],     [𝐩],
      [$bold(Q)$],     [𝐐],        [$bold(q)$],     [𝐪],
      [$bold(R)$],     [𝐑],        [$bold(r)$],     [𝐫],
      [$bold(S)$],     [𝐒],        [$bold(s)$],     [𝐬],
      [$bold(T)$],     [𝐓],        [$bold(t)$],     [𝐭],
      [$bold(U)$],     [𝐔],        [$bold(u)$],     [𝐮],
      [$bold(V)$],     [𝐕],        [$bold(v)$],     [𝐯],
      [$bold(W)$],     [𝐖],        [$bold(w)$],     [𝐰],
      [$bold(X)$],     [𝐗],        [$bold(x)$],     [𝐱],
      [$bold(Y)$],     [𝐘],        [$bold(y)$],     [𝐲],
      [$bold(Z)$],     [𝐙],        [$bold(z)$],     [𝐳],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*],   [*Symbol*], [*Greek Lower*],       [*Symbol*],
      [$bold(Alpha)$],   [𝚨],        [$bold(alpha)$],       [𝜶],
      [$bold(Beta)$],    [𝚩],        [$bold(beta)$],        [𝜷],
      [$bold(Gamma)$],   [𝚪],        [$bold(gamma)$],       [𝜸],
      [$bold(Delta)$],   [𝚫],        [$bold(delta)$],       [𝜹],
      [$bold(Digamma)$], [$ 𝟊 $],        [$bold(digamma)$],     [$ 𝟋 $],
      [$bold(Epsilon)$], [𝚬],        [$bold(epsilon)$],     [𝜺],
      [$bold(Zeta)$],    [𝚭],        [$bold(zeta)$],        [𝜻],
      [$bold(Eta)$],     [𝚮],        [$bold(eta)$],         [𝜼],
      [$bold(Theta)$],   [𝚯],        [$bold(theta)$],       [𝜽],
      [$bold(Iota)$],    [𝚰],        [$bold(iota)$],        [𝜾],
      [$bold(Kappa)$],   [𝚱],        [$bold(kappa)$],       [𝜿],
      [$bold(Lambda)$],  [𝚲],        [$bold(lambda)$],      [𝝀],
      [$bold(Mu)$],      [𝚳],        [$bold(mu)$],          [𝝁],
      [$bold(Nu)$],      [𝚴],        [$bold(nu)$],          [𝝂],
      [$bold(Xi)$],      [𝚵],        [$bold(xi)$],          [𝝃],
      [$bold(Omicron)$], [𝚶],        [$bold(omicron)$],     [𝝄],
      [$bold(Pi)$],      [𝚷],        [$bold(pi)$],          [𝝅],
      [$bold(Rho)$],     [𝚸],        [$bold(rho)$],         [𝝆],
      [$bold(Sigma)$],   [𝚺],        [$bold(sigma)$],       [𝝈],
      [$bold(Tau)$],     [𝚻],        [$bold(tau)$],         [𝝉],
      [$bold(Upsilon)$], [𝚼],        [$bold(upsilon)$],     [𝝊],
      [$bold(Phi)$],     [𝚽],        [$bold(phi)$],         [𝝋],
      [$bold(Chi)$],     [𝚾],        [$bold(chi)$],         [𝝌],
      [$bold(Psi)$],     [𝚿],        [$bold(psi)$],         [𝝍],
      [$bold(Omega)$],   [𝛀],        [$bold(omega)$],       [𝝎],
      [],                [],         [$bold(epsilon.alt)$], [𝝐],
      [],                [],         [$bold(Theta.alt)$],   [𝚹],
      [],                [],         [$bold(theta.alt)$],   [𝝑],
      [],                [],         [$bold(kappa.alt)$],   [𝝒],
      [],                [],         [$bold(pi.alt)$],      [𝝕],
      [],                [],         [$bold(rho.alt)$],     [𝝔],
      [],                [],         [$bold(sigma.alt)$],   [𝝇],
      [],                [],         [$bold(phi.alt)$],     [𝝓],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*],  [*Symbol*],
      [$bold(0)$], [𝟎],
      [$bold(1)$], [𝟏],
      [$bold(2)$], [𝟐],
      [$bold(3)$], [𝟑],
      [$bold(4)$], [𝟒],
      [$bold(5)$], [𝟓],
      [$bold(6)$], [𝟔],
      [$bold(7)$], [𝟕],
      [$bold(8)$], [𝟖],
      [$bold(9)$], [𝟗],
    )
  ],
)

#pagebreak()

= Calligraphic (cal)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$cal(A)$],      [𝒜],        [$cal(a)$],      [𝒶],
      [$cal(B)$],      [ℬ],        [$cal(b)$],      [𝒷],
      [$cal(C)$],      [𝒞],        [$cal(c)$],      [𝒸],
      [$cal(D)$],      [𝒟],        [$cal(d)$],      [𝒹],
      [$cal(E)$],      [ℰ],        [$cal(e)$],      [ℯ],
      [$cal(F)$],      [ℱ],        [$cal(f)$],      [𝒻],
      [$cal(G)$],      [𝒢],        [$cal(g)$],      [ℊ],
      [$cal(H)$],      [ℋ],        [$cal(h)$],      [𝒽],
      [$cal(I)$],      [ℐ],        [$cal(i)$],      [𝒾],
      [$cal(J)$],      [𝒥],        [$cal(j)$],      [𝒿],
      [$cal(K)$],      [𝒦],        [$cal(k)$],      [𝓀],
      [$cal(L)$],      [ℒ],        [$cal(l)$],      [𝓁],
      [$cal(M)$],      [ℳ],        [$cal(m)$],      [𝓂],
      [$cal(N)$],      [𝒩],        [$cal(n)$],      [𝓃],
      [$cal(O)$],      [𝒪],        [$cal(o)$],      [ℴ],
      [$cal(P)$],      [𝒫],        [$cal(p)$],      [𝓅],
      [$cal(Q)$],      [𝒬],        [$cal(q)$],      [𝓆],
      [$cal(R)$],      [ℛ],        [$cal(r)$],      [𝓇],
      [$cal(S)$],      [𝒮],        [$cal(s)$],      [𝓈],
      [$cal(T)$],      [𝒯],        [$cal(t)$],      [𝓉],
      [$cal(U)$],      [𝒰],        [$cal(u)$],      [𝓊],
      [$cal(V)$],      [𝒱],        [$cal(v)$],      [𝓋],
      [$cal(W)$],      [𝒲],        [$cal(w)$],      [𝓌],
      [$cal(X)$],      [𝒳],        [$cal(x)$],      [𝓍],
      [$cal(Y)$],      [𝒴],        [$cal(y)$],      [𝓎],
      [$cal(Z)$],      [𝒵],        [$cal(z)$],      [𝓏],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*],  [*Symbol*], [*Greek Lower*],      [*Symbol*],
      [$cal(Alpha)$],   [$ Α $],        [$cal(alpha)$],       [$ 𝛼 $],
      [$cal(Beta)$],    [$ Β $],        [$cal(beta)$],        [$ 𝛽 $],
      [$cal(Gamma)$],   [$ Γ $],        [$cal(gamma)$],       [$ 𝛾 $],
      [$cal(Delta)$],   [$ Δ $],        [$cal(delta)$],       [$ 𝛿 $],
      [$cal(Digamma)$], [$ Ϝ $],        [$cal(digamma)$],     [$ ϝ $],
      [$cal(Epsilon)$], [$ Ε $],        [$cal(epsilon)$],     [$ 𝜀 $],
      [$cal(Zeta)$],    [$ Ζ $],        [$cal(zeta)$],        [$ 𝜁 $],
      [$cal(Eta)$],     [$ Η $],        [$cal(eta)$],         [$ 𝜂 $],
      [$cal(Theta)$],   [$ Θ $],        [$cal(theta)$],       [$ 𝜃 $],
      [$cal(Iota)$],    [$ Ι $],        [$cal(iota)$],        [$ 𝜄 $],
      [$cal(Kappa)$],   [$ Κ $],        [$cal(kappa)$],       [$ 𝜅 $],
      [$cal(Lambda)$],  [$ Λ $],        [$cal(lambda)$],      [$ 𝜆 $],
      [$cal(Mu)$],      [$ Μ $],        [$cal(mu)$],          [$ 𝜇 $],
      [$cal(Nu)$],      [$ Ν $],        [$cal(nu)$],          [$ 𝜈 $],
      [$cal(Xi)$],      [$ Ξ $],        [$cal(xi)$],          [$ 𝜉 $],
      [$cal(Omicron)$], [$ Ο $],        [$cal(omicron)$],     [$ 𝜊 $],
      [$cal(Pi)$],      [$ Π $],        [$cal(pi)$],          [$ 𝜋 $],
      [$cal(Rho)$],     [$ Ρ $],        [$cal(rho)$],         [$ 𝜌 $],
      [$cal(Sigma)$],   [$ Σ $],        [$cal(sigma)$],       [$ 𝜎 $],
      [$cal(Tau)$],     [$ Τ $],        [$cal(tau)$],         [$ 𝜏 $],
      [$cal(Upsilon)$], [$ Υ $],        [$cal(upsilon)$],     [$ 𝜐 $],
      [$cal(Phi)$],     [$ Φ $],        [$cal(phi)$],         [$ 𝜑 $],
      [$cal(Chi)$],     [$ Χ $],        [$cal(chi)$],         [$ 𝜒 $],
      [$cal(Psi)$],     [$ Ψ $],        [$cal(psi)$],         [$ 𝜓 $],
      [$cal(Omega)$],   [$ Ω $],        [$cal(omega)$],       [$ 𝜔 $],
      [],               [],         [$cal(epsilon.alt)$], [$ 𝜖 $],
      [],               [],         [$cal(Theta.alt)$],   [$ ϴ $],
      [],               [],         [$cal(theta.alt)$],   [$ 𝜗 $],
      [],               [],         [$cal(kappa.alt)$],   [$ 𝜘 $],
      [],               [],         [$cal(pi.alt)$],      [$ 𝜛 $],
      [],               [],         [$cal(rho.alt)$],     [$ 𝜚 $],
      [],               [],         [$cal(sigma.alt)$],   [$ 𝜍 $],
      [],               [],         [$cal(phi.alt)$],     [$ 𝜙 $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$cal(0)$], [𝟶],
      [$cal(1)$], [𝟷],
      [$cal(2)$], [𝟸],
      [$cal(3)$], [𝟹],
      [$cal(4)$], [𝟺],
      [$cal(5)$], [𝟻],
      [$cal(6)$], [𝟼],
      [$cal(7)$], [𝟽],
      [$cal(8)$], [𝟾],
      [$cal(9)$], [𝟿],
    )
  ],
)

#pagebreak()

= Fraktur (frak)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$frak(A)$], [𝔄], [$frak(a)$], [𝔞],
      [$frak(B)$], [𝔅], [$frak(b)$], [𝔟],
      [$frak(C)$], [ℭ], [$frak(c)$], [𝔠],
      [$frak(D)$], [𝔇], [$frak(d)$], [𝔡],
      [$frak(E)$], [𝔈], [$frak(e)$], [𝔢],
      [$frak(F)$], [𝔉], [$frak(f)$], [𝔣],
      [$frak(G)$], [𝔊], [$frak(g)$], [𝔤],
      [$frak(H)$], [ℌ], [$frak(h)$], [𝔥],
      [$frak(I)$], [ℑ], [$frak(i)$], [𝔦],
      [$frak(J)$], [𝔍], [$frak(j)$], [𝔧],
      [$frak(K)$], [𝔎], [$frak(k)$], [𝔨],
      [$frak(L)$], [𝔏], [$frak(l)$], [𝔩],
      [$frak(M)$], [𝔐], [$frak(m)$], [𝔪],
      [$frak(N)$], [𝔑], [$frak(n)$], [𝔫],
      [$frak(O)$], [𝔒], [$frak(o)$], [𝔬],
      [$frak(P)$], [𝔓], [$frak(p)$], [𝔭],
      [$frak(Q)$], [𝔔], [$frak(q)$], [𝔮],
      [$frak(R)$], [ℜ], [$frak(r)$], [𝔯],
      [$frak(S)$], [𝔖], [$frak(s)$], [𝔰],
      [$frak(T)$], [𝔗], [$frak(t)$], [𝔱],
      [$frak(U)$], [𝔘], [$frak(u)$], [𝔲],
      [$frak(V)$], [𝔙], [$frak(v)$], [𝔳],
      [$frak(W)$], [𝔚], [$frak(w)$], [𝔴],
      [$frak(X)$], [𝔛], [$frak(x)$], [𝔵],
      [$frak(Y)$], [𝔜], [$frak(y)$], [𝔶],
      [$frak(Z)$], [ℨ], [$frak(z)$], [𝔷],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*], [*Symbol*],
      [$frak(Alpha)$], [$ Α $], [$frak(alpha)$], [$ 𝛼 $],
      [$frak(Beta)$], [$ Β $], [$frak(beta)$], [$ 𝛽 $],
      [$frak(Gamma)$], [$ Γ $], [$frak(gamma)$], [$ 𝛾 $],
      [$frak(Delta)$], [$ Δ $], [$frak(delta)$], [$ 𝛿 $],
      [$frak(Digamma)$], [$ Ϝ $], [$frak(digamma)$], [$ ϝ $],
      [$frak(Epsilon)$], [$ Ε $], [$frak(epsilon)$], [$ 𝜀 $],
      [$frak(Zeta)$], [$ Ζ $], [$frak(zeta)$], [$ 𝜁 $],
      [$frak(Eta)$], [$ Η $], [$frak(eta)$], [$ 𝜂 $],
      [$frak(Theta)$], [$ Θ $], [$frak(theta)$], [$ 𝜃 $],
      [$frak(Iota)$], [$ Ι $], [$frak(iota)$], [$ 𝜄 $],
      [$frak(Kappa)$], [$ Κ $], [$frak(kappa)$], [$ 𝜅 $],
      [$frak(Lambda)$], [$ Λ $], [$frak(lambda)$], [$ 𝜆 $],
      [$frak(Mu)$], [$ Μ $], [$frak(mu)$], [$ 𝜇 $],
      [$frak(Nu)$], [$ Ν $], [$frak(nu)$], [$ 𝜈 $],
      [$frak(Xi)$], [$ Ξ $], [$frak(xi)$], [$ 𝜉 $],
      [$frak(Omicron)$], [$ Ο $], [$frak(omicron)$], [$ 𝜊 $],
      [$frak(Pi)$], [$ Π $], [$frak(pi)$], [$ 𝜋 $],
      [$frak(Rho)$], [$ Ρ $], [$frak(rho)$], [$ 𝜌 $],
      [$frak(Sigma)$], [$ Σ $], [$frak(sigma)$], [$ 𝜎 $],
      [$frak(Tau)$], [$ Τ $], [$frak(tau)$], [$ 𝜏 $],
      [$frak(Upsilon)$], [$ Υ $], [$frak(upsilon)$], [$ 𝜐 $],
      [$frak(Phi)$], [$ Φ $], [$frak(phi)$], [$ 𝜑 $],
      [$frak(Chi)$], [$ Χ $], [$frak(chi)$], [$ 𝜒 $],
      [$frak(Psi)$], [$ Ψ $], [$frak(psi)$], [$ 𝜓 $],
      [$frak(Omega)$], [$ Ω $], [$frak(omega)$], [$ 𝜔 $],
      [], [], [$frak(epsilon.alt)$], [$ 𝜖 $],
      [], [], [$frak(Theta.alt)$], [$ ϴ $],
      [], [], [$frak(theta.alt)$], [$ 𝜗 $],
      [], [], [$frak(kappa.alt)$], [$ 𝜘 $],
      [], [], [$frak(pi.alt)$], [$ 𝜛 $],
      [], [], [$frak(rho.alt)$], [$ 𝜚 $],
      [], [], [$frak(sigma.alt)$], [$ 𝜍 $],
      [], [], [$frak(phi.alt)$], [$ 𝜙 $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$frak(0)$], [𝟶],
      [$frak(1)$], [𝟷],
      [$frak(2)$], [𝟸],
      [$frak(3)$], [𝟹],
      [$frak(4)$], [𝟺],
      [$frak(5)$], [𝟻],
      [$frak(6)$], [𝟼],
      [$frak(7)$], [𝟽],
      [$frak(8)$], [𝟾],
      [$frak(9)$], [𝟿],
    )
  ],
)

#pagebreak()

= Italic (italic)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$italic(A)$], [𝐴], [$italic(a)$], [𝑎],
      [$italic(B)$], [𝐵], [$italic(b)$], [𝑏],
      [$italic(C)$], [𝐶], [$italic(c)$], [𝑐],
      [$italic(D)$], [𝐷], [$italic(d)$], [𝑑],
      [$italic(E)$], [𝐸], [$italic(e)$], [𝑒],
      [$italic(F)$], [𝐹], [$italic(f)$], [𝑓],
      [$italic(G)$], [𝐺], [$italic(g)$], [𝑔],
      [$italic(H)$], [𝐻], [$italic(h)$], [ℎ],
      [$italic(I)$], [𝐼], [$italic(i)$], [𝑖],
      [$italic(J)$], [𝐽], [$italic(j)$], [𝑗],
      [$italic(K)$], [𝐾], [$italic(k)$], [𝑘],
      [$italic(L)$], [𝐿], [$italic(l)$], [𝑙],
      [$italic(M)$], [𝑀], [$italic(m)$], [𝑚],
      [$italic(N)$], [𝑁], [$italic(n)$], [𝑛],
      [$italic(O)$], [𝑂], [$italic(o)$], [𝑜],
      [$italic(P)$], [𝑃], [$italic(p)$], [𝑝],
      [$italic(Q)$], [𝑄], [$italic(q)$], [𝑞],
      [$italic(R)$], [𝑅], [$italic(r)$], [𝑟],
      [$italic(S)$], [𝑆], [$italic(s)$], [𝑠],
      [$italic(T)$], [𝑇], [$italic(t)$], [𝑡],
      [$italic(U)$], [𝑈], [$italic(u)$], [𝑢],
      [$italic(V)$], [𝑉], [$italic(v)$], [𝑣],
      [$italic(W)$], [𝑊], [$italic(w)$], [𝑤],
      [$italic(X)$], [𝑋], [$italic(x)$], [𝑥],
      [$italic(Y)$], [𝑌], [$italic(y)$], [𝑦],
      [$italic(Z)$], [𝑍], [$italic(z)$], [𝑧],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*], [*Symbol*],
      [$italic(Alpha)$], [$ 𝛢 $], [$italic(alpha)$], [$ 𝛼 $],
      [$italic(Beta)$], [$ 𝛣 $], [$italic(beta)$], [$ 𝛽 $],
      [$italic(Gamma)$], [$ 𝛤 $], [$italic(gamma)$], [$ 𝛾 $],
      [$italic(Delta)$], [$ 𝛥 $], [$italic(delta)$], [$ 𝛿 $],
      [$italic(Digamma)$], [$ Ϝ $], [$italic(digamma)$], [$ ϝ $],
      [$italic(Epsilon)$], [$ 𝛦 $], [$italic(epsilon)$], [$ 𝜀 $],
      [$italic(Zeta)$], [$ 𝛧 $], [$italic(zeta)$], [$ 𝜁 $],
      [$italic(Eta)$], [$ 𝛨 $], [$italic(eta)$], [$ 𝜂 $],
      [$italic(Theta)$], [$ 𝛩 $], [$italic(theta)$], [$ 𝜃 $],
      [$italic(Iota)$], [$ 𝛪 $], [$italic(iota)$], [$ 𝜄 $],
      [$italic(Kappa)$], [$ 𝛫 $], [$italic(kappa)$], [$ 𝜅 $],
      [$italic(Lambda)$], [$ 𝛬 $], [$italic(lambda)$], [$ 𝜆 $],
      [$italic(Mu)$], [$ 𝛭 $], [$italic(mu)$], [$ 𝜇 $],
      [$italic(Nu)$], [$ 𝛮 $], [$italic(nu)$], [$ 𝜈 $],
      [$italic(Xi)$], [$ 𝛯 $], [$italic(xi)$], [$ 𝜉 $],
      [$italic(Omicron)$], [$ 𝛰 $], [$italic(omicron)$], [$ 𝜊 $],
      [$italic(Pi)$], [$ 𝛱 $], [$italic(pi)$], [$ 𝜋 $],
      [$italic(Rho)$], [$ 𝛲 $], [$italic(rho)$], [$ 𝜌 $],
      [$italic(Sigma)$], [$ 𝛴 $], [$italic(sigma)$], [$ 𝜎 $],
      [$italic(Tau)$], [$ 𝛵 $], [$italic(tau)$], [$ 𝜏 $],
      [$italic(Upsilon)$], [$ 𝛶 $], [$italic(upsilon)$], [$ 𝜐 $],
      [$italic(Phi)$], [$ 𝛷 $], [$italic(phi)$], [$ 𝜑 $],
      [$italic(Chi)$], [$ 𝛸 $], [$italic(chi)$], [$ 𝜒 $],
      [$italic(Psi)$], [$ 𝛹 $], [$italic(psi)$], [$ 𝜓 $],
      [$italic(Omega)$], [$ 𝛺 $], [$italic(omega)$], [$ 𝜔 $],
      [], [], [$italic(epsilon.alt)$], [$ 𝜖 $],
      [], [], [$italic(Theta.alt)$], [$ 𝛳 $],
      [], [], [$italic(theta.alt)$], [$ 𝜗 $],
      [], [], [$italic(kappa.alt)$], [$ 𝜘 $],
      [], [], [$italic(pi.alt)$], [$ 𝜛 $],
      [], [], [$italic(rho.alt)$], [$ 𝜚 $],
      [], [], [$italic(sigma.alt)$], [$ 𝜍 $],
      [], [], [$italic(phi.alt)$], [$ 𝜙 $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$italic(0)$], [𝟶],
      [$italic(1)$], [𝟷],
      [$italic(2)$], [𝟸],
      [$italic(3)$], [𝟹],
      [$italic(4)$], [𝟺],
      [$italic(5)$], [𝟻],
      [$italic(6)$], [𝟼],
      [$italic(7)$], [𝟽],
      [$italic(8)$], [𝟾],
      [$italic(9)$], [𝟿],
    )
  ],
)

#pagebreak()

= Monospace (mono)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$mono(A)$], [𝙰], [$mono(a)$], [𝚊],
      [$mono(B)$], [𝙱], [$mono(b)$], [𝚋],
      [$mono(C)$], [𝙲], [$mono(c)$], [𝚌],
      [$mono(D)$], [𝙳], [$mono(d)$], [𝚍],
      [$mono(E)$], [𝙴], [$mono(e)$], [𝚎],
      [$mono(F)$], [𝙵], [$mono(f)$], [𝚏],
      [$mono(G)$], [𝙶], [$mono(g)$], [𝚐],
      [$mono(H)$], [𝙷], [$mono(h)$], [𝚑],
      [$mono(I)$], [𝙸], [$mono(i)$], [𝚒],
      [$mono(J)$], [𝙹], [$mono(j)$], [𝚓],
      [$mono(K)$], [𝙺], [$mono(k)$], [𝚔],
      [$mono(L)$], [𝙻], [$mono(l)$], [𝚕],
      [$mono(M)$], [𝙼], [$mono(m)$], [𝚖],
      [$mono(N)$], [𝙽], [$mono(n)$], [𝚗],
      [$mono(O)$], [𝙾], [$mono(o)$], [𝚘],
      [$mono(P)$], [𝙿], [$mono(p)$], [𝚙],
      [$mono(Q)$], [𝚀], [$mono(q)$], [𝚚],
      [$mono(R)$], [𝚁], [$mono(r)$], [𝚛],
      [$mono(S)$], [𝚂], [$mono(s)$], [𝚜],
      [$mono(T)$], [𝚃], [$mono(t)$], [𝚝],
      [$mono(U)$], [𝚄], [$mono(u)$], [𝚞],
      [$mono(V)$], [𝚅], [$mono(v)$], [𝚟],
      [$mono(W)$], [𝚆], [$mono(w)$], [𝚠],
      [$mono(X)$], [𝚇], [$mono(x)$], [𝚡],
      [$mono(Y)$], [𝚈], [$mono(y)$], [𝚢],
      [$mono(Z)$], [𝚉], [$mono(z)$], [𝚣],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*], [*Symbol*],
      [$mono(Alpha)$], [$ Α $], [$mono(alpha)$], [$ 𝛼 $],
      [$mono(Beta)$], [$ Β $], [$mono(beta)$], [$ 𝛽 $],
      [$mono(Gamma)$], [$ Γ $], [$mono(gamma)$], [$ 𝛾 $],
      [$mono(Delta)$], [$ Δ $], [$mono(delta)$], [$ 𝛿 $],
      [$mono(Digamma)$], [$ Ϝ $], [$mono(digamma)$], [$ ϝ $],
      [$mono(Epsilon)$], [$ Ε $], [$mono(epsilon)$], [$ 𝜀 $],
      [$mono(Zeta)$], [$ Ζ $], [$mono(zeta)$], [$ 𝜁 $],
      [$mono(Eta)$], [$ Η $], [$mono(eta)$], [$ 𝜂 $],
      [$mono(Theta)$], [$ Θ $], [$mono(theta)$], [$ 𝜃 $],
      [$mono(Iota)$], [$ Ι $], [$mono(iota)$], [$ 𝜄 $],
      [$mono(Kappa)$], [$ Κ $], [$mono(kappa)$], [$ 𝜅 $],
      [$mono(Lambda)$], [$ Λ $], [$mono(lambda)$], [$ 𝜆 $],
      [$mono(Mu)$], [$ Μ $], [$mono(mu)$], [$ 𝜇 $],
      [$mono(Nu)$], [$ Ν $], [$mono(nu)$], [$ 𝜈 $],
      [$mono(Xi)$], [$ Ξ $], [$mono(xi)$], [$ 𝜉 $],
      [$mono(Omicron)$], [$ Ο $], [$mono(omicron)$], [$ 𝜊 $],
      [$mono(Pi)$], [$ Π $], [$mono(pi)$], [$ 𝜋 $],
      [$mono(Rho)$], [$ Ρ $], [$mono(rho)$], [$ 𝜌 $],
      [$mono(Sigma)$], [$ Σ $], [$mono(sigma)$], [$ 𝜎 $],
      [$mono(Tau)$], [$ Τ $], [$mono(tau)$], [$ 𝜏 $],
      [$mono(Upsilon)$], [$ Υ $], [$mono(upsilon)$], [$ 𝜐 $],
      [$mono(Phi)$], [$ Φ $], [$mono(phi)$], [$ 𝜑 $],
      [$mono(Chi)$], [$ Χ $], [$mono(chi)$], [$ 𝜒 $],
      [$mono(Psi)$], [$ Ψ $], [$mono(psi)$], [$ 𝜓 $],
      [$mono(Omega)$], [$ Ω $], [$mono(omega)$], [$ 𝜔 $],
      [], [], [$mono(epsilon.alt)$], [$ 𝜖 $],
      [], [], [$mono(Theta.alt)$], [$ ϴ $],
      [], [], [$mono(theta.alt)$], [$ 𝜗 $],
      [], [], [$mono(kappa.alt)$], [$ 𝜘 $],
      [], [], [$mono(pi.alt)$], [$ 𝜛 $],
      [], [], [$mono(rho.alt)$], [$ 𝜚 $],
      [], [], [$mono(sigma.alt)$], [$ 𝜍 $],
      [], [], [$mono(phi.alt)$], [$ 𝜙 $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$mono(0)$], [𝟶],
      [$mono(1)$], [𝟷],
      [$mono(2)$], [𝟸],
      [$mono(3)$], [𝟹],
      [$mono(4)$], [𝟺],
      [$mono(5)$], [𝟻],
      [$mono(6)$], [𝟼],
      [$mono(7)$], [𝟽],
      [$mono(8)$], [𝟾],
      [$mono(9)$], [𝟿],
    )
  ],
)

#pagebreak()

= Sans-serif (sans)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$sans(A)$], [𝖠], [$sans(a)$], [𝖺],
      [$sans(B)$], [𝖡], [$sans(b)$], [𝖻],
      [$sans(C)$], [𝖢], [$sans(c)$], [𝖼],
      [$sans(D)$], [𝖣], [$sans(d)$], [𝖽],
      [$sans(E)$], [𝖤], [$sans(e)$], [𝖾],
      [$sans(F)$], [𝖥], [$sans(f)$], [𝖿],
      [$sans(G)$], [𝖦], [$sans(g)$], [𝗀],
      [$sans(H)$], [𝖧], [$sans(h)$], [𝗁],
      [$sans(I)$], [𝖨], [$sans(i)$], [𝗂],
      [$sans(J)$], [𝖩], [$sans(j)$], [𝗃],
      [$sans(K)$], [𝖪], [$sans(k)$], [𝗄],
      [$sans(L)$], [𝖫], [$sans(l)$], [𝗅],
      [$sans(M)$], [𝖬], [$sans(m)$], [𝗆],
      [$sans(N)$], [𝖭], [$sans(n)$], [𝗇],
      [$sans(O)$], [𝖮], [$sans(o)$], [𝗈],
      [$sans(P)$], [𝖯], [$sans(p)$], [𝗉],
      [$sans(Q)$], [𝖰], [$sans(q)$], [𝗊],
      [$sans(R)$], [𝖱], [$sans(r)$], [𝗋],
      [$sans(S)$], [𝖲], [$sans(s)$], [𝗌],
      [$sans(T)$], [𝖳], [$sans(t)$], [𝗍],
      [$sans(U)$], [𝖴], [$sans(u)$], [𝗎],
      [$sans(V)$], [𝖵], [$sans(v)$], [𝗏],
      [$sans(W)$], [𝖶], [$sans(w)$], [𝗐],
      [$sans(X)$], [𝖷], [$sans(x)$], [𝗑],
      [$sans(Y)$], [𝖸], [$sans(y)$], [𝗒],
      [$sans(Z)$], [𝖹], [$sans(z)$], [𝗓],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*], [*Symbol*],
      [$sans(Alpha)$], [$ 𝝖 $], [$sans(alpha)$], [$ 𝞪 $],
      [$sans(Beta)$], [$ 𝝗 $], [$sans(beta)$], [$ 𝞫 $],
      [$sans(Gamma)$], [$ 𝝘 $], [$sans(gamma)$], [$ 𝞬 $],
      [$sans(Delta)$], [$ 𝝙 $], [$sans(delta)$], [$ 𝞭 $],
      [$sans(Digamma)$], [$ 𝟊 $], [$sans(digamma)$], [$ 𝟋 $],
      [$sans(Epsilon)$], [$ 𝝚 $], [$sans(epsilon)$], [$ 𝞮 $],
      [$sans(Zeta)$], [$ 𝝛 $], [$sans(zeta)$], [$ 𝞯 $],
      [$sans(Eta)$], [$ 𝝜 $], [$sans(eta)$], [$ 𝞰 $],
      [$sans(Theta)$], [$ 𝝝 $], [$sans(theta)$], [$ 𝞱 $],
      [$sans(Iota)$], [$ 𝝞 $], [$sans(iota)$], [$ 𝞲 $],
      [$sans(Kappa)$], [$ 𝝟 $], [$sans(kappa)$], [$ 𝞳 $],
      [$sans(Lambda)$], [$ 𝝠 $], [$sans(lambda)$], [$ 𝞴 $],
      [$sans(Mu)$], [$ 𝝡 $], [$sans(mu)$], [$ 𝞵 $],
      [$sans(Nu)$], [$ 𝝢 $], [$sans(nu)$], [$ 𝞶 $],
      [$sans(Xi)$], [$ 𝝣 $], [$sans(xi)$], [$ 𝞷 $],
      [$sans(Omicron)$], [$ 𝝤 $], [$sans(omicron)$], [$ 𝞸 $],
      [$sans(Pi)$], [$ 𝝥 $], [$sans(pi)$], [$ 𝞹 $],
      [$sans(Rho)$], [$ 𝝦 $], [$sans(rho)$], [$ 𝞺 $],
      [$sans(Sigma)$], [$ 𝝨 $], [$sans(sigma)$], [$ 𝞼 $],
      [$sans(Tau)$], [$ 𝝩 $], [$sans(tau)$], [$ 𝞽 $],
      [$sans(Upsilon)$], [$ 𝝪 $], [$sans(upsilon)$], [$ 𝞾 $],
      [$sans(Phi)$], [$ 𝝫 $], [$sans(phi)$], [$ 𝞿 $],
      [$sans(Chi)$], [$ 𝝬 $], [$sans(chi)$], [$ 𝟀 $],
      [$sans(Psi)$], [$ 𝝭 $], [$sans(psi)$], [$ 𝟁 $],
      [$sans(Omega)$], [$ 𝝮 $], [$sans(omega)$], [$ 𝟂 $],
      [], [], [$sans(epsilon.alt)$], [$ 𝞊 $],
      [], [], [$sans(Theta.alt)$], [𝝧],
      [], [], [$sans(theta.alt)$], [𝟅],
      [], [], [$sans(kappa.alt)$], [𝟆],
      [], [], [$sans(pi.alt)$], [𝟉],
      [], [], [$sans(rho.alt)$], [𝟈],
      [], [], [$sans(sigma.alt)$], [$ 𝞁 $],
      [], [], [$sans(phi.alt)$], [𝟇],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$sans(0)$], [𝟢],
      [$sans(1)$], [𝟣],
      [$sans(2)$], [𝟤],
      [$sans(3)$], [𝟥],
      [$sans(4)$], [𝟦],
      [$sans(5)$], [𝟧],
      [$sans(6)$], [𝟨],
      [$sans(7)$], [𝟩],
      [$sans(8)$], [𝟪],
      [$sans(9)$], [𝟫],
    )
  ],
)

#pagebreak()
= Script (scr)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$scr(A)$], [𝒜], [$scr(a)$], [𝒶],
      [$scr(B)$], [ℬ], [$scr(b)$], [𝒷],
      [$scr(C)$], [𝒞], [$scr(c)$], [𝒸],
      [$scr(D)$], [𝒟], [$scr(d)$], [𝒹],
      [$scr(E)$], [ℰ], [$scr(e)$], [ℯ],
      [$scr(F)$], [ℱ], [$scr(f)$], [𝒻],
      [$scr(G)$], [𝒢], [$scr(g)$], [ℊ],
      [$scr(H)$], [ℋ], [$scr(h)$], [𝒽],
      [$scr(I)$], [ℐ], [$scr(i)$], [𝒾],
      [$scr(J)$], [𝒥], [$scr(j)$], [𝒿],
      [$scr(K)$], [𝒦], [$scr(k)$], [𝓀],
      [$scr(L)$], [ℒ], [$scr(l)$], [𝓁],
      [$scr(M)$], [ℳ], [$scr(m)$], [𝓂],
      [$scr(N)$], [𝒩], [$scr(n)$], [𝓃],
      [$scr(O)$], [𝒪], [$scr(o)$], [ℴ],
      [$scr(P)$], [𝒫], [$scr(p)$], [𝓅],
      [$scr(Q)$], [𝒬], [$scr(q)$], [𝓆],
      [$scr(R)$], [ℛ], [$scr(r)$], [𝓇],
      [$scr(S)$], [𝒮], [$scr(s)$], [𝓈],
      [$scr(T)$], [𝒯], [$scr(t)$], [𝓉],
      [$scr(U)$], [𝒰], [$scr(u)$], [𝓊],
      [$scr(V)$], [𝒱], [$scr(v)$], [𝓋],
      [$scr(W)$], [𝒲], [$scr(w)$], [𝓌],
      [$scr(X)$], [𝒳], [$scr(x)$], [𝓍],
      [$scr(Y)$], [𝒴], [$scr(y)$], [𝓎],
      [$scr(Z)$], [𝒵], [$scr(z)$], [𝓏],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*], [*Symbol*],
      [$scr(Alpha)$], [$ Α $], [$scr(alpha)$], [$ 𝛼 $],
      [$scr(Beta)$], [$ Β $], [$scr(beta)$], [$ 𝛽 $],
      [$scr(Gamma)$], [$ Γ $], [$scr(gamma)$], [$ 𝛾 $],
      [$scr(Delta)$], [$ Δ $], [$scr(delta)$], [$ 𝛿 $],
      [$scr(Digamma)$], [$ Ϝ $], [$scr(digamma)$], [$ ϝ $],
      [$scr(Epsilon)$], [$ Ε $], [$scr(epsilon)$], [$ 𝜀 $],
      [$scr(Zeta)$], [$ Ζ $], [$scr(zeta)$], [$ 𝜁 $],
      [$scr(Eta)$], [$ Η $], [$scr(eta)$], [$ 𝜂 $],
      [$scr(Theta)$], [$ Θ $], [$scr(theta)$], [$ 𝜃 $],
      [$scr(Iota)$], [$ Ι $], [$scr(iota)$], [$ 𝜄 $],
      [$scr(Kappa)$], [$ Κ $], [$scr(kappa)$], [$ 𝜅 $],
      [$scr(Lambda)$], [$ Λ $], [$scr(lambda)$], [$ 𝜆 $],
      [$scr(Mu)$], [$ Μ $], [$scr(mu)$], [$ 𝜇 $],
      [$scr(Nu)$], [$ Ν $], [$scr(nu)$], [$ 𝜈 $],
      [$scr(Xi)$], [$ Ξ $], [$scr(xi)$], [$ 𝜉 $],
      [$scr(Omicron)$], [$ Ο $], [$scr(omicron)$], [$ 𝜊 $],
      [$scr(Pi)$], [$ Π $], [$scr(pi)$], [$ 𝜋 $],
      [$scr(Rho)$], [$ Ρ $], [$scr(rho)$], [$ 𝜌 $],
      [$scr(Sigma)$], [$ Σ $], [$scr(sigma)$], [$ 𝜎 $],
      [$scr(Tau)$], [$ Τ $], [$scr(tau)$], [$ 𝜏 $],
      [$scr(Upsilon)$], [$ Υ $], [$scr(upsilon)$], [$ 𝜐 $],
      [$scr(Phi)$], [$ Φ $], [$scr(phi)$], [$ 𝜑 $],
      [$scr(Chi)$], [$ Χ $], [$scr(chi)$], [$ 𝜒 $],
      [$scr(Psi)$], [$ Ψ $], [$scr(psi)$], [$ 𝜓 $],
      [$scr(Omega)$], [$ Ω $], [$scr(omega)$], [$ 𝜔 $],
      [], [], [$scr(epsilon.alt)$], [$ 𝜖 $],
      [], [], [$scr(Theta.alt)$], [$ ϴ $],
      [], [], [$scr(theta.alt)$], [$ 𝜗 $],
      [], [], [$scr(kappa.alt)$], [$ 𝜘 $],
      [], [], [$scr(pi.alt)$], [$ 𝜛 $],
      [], [], [$scr(rho.alt)$], [$ 𝜚 $],
      [], [], [$scr(sigma.alt)$], [$ 𝜍 $],
      [], [], [$scr(phi.alt)$], [$ 𝜙 $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$scr(0)$], [𝟶],
      [$scr(1)$], [𝟷],
      [$scr(2)$], [𝟸],
      [$scr(3)$], [𝟹],
      [$scr(4)$], [𝟺],
      [$scr(5)$], [𝟻],
      [$scr(6)$], [𝟼],
      [$scr(7)$], [𝟽],
      [$scr(8)$], [𝟾],
      [$scr(9)$], [𝟿],
    )
  ],
)

#pagebreak()

= Serif (serif)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$serif(A)$], [𝐴], [$serif(a)$], [𝑎],
      [$serif(B)$], [𝐵], [$serif(b)$], [𝑏],
      [$serif(C)$], [𝐶], [$serif(c)$], [𝑐],
      [$serif(D)$], [𝐷], [$serif(d)$], [𝑑],
      [$serif(E)$], [𝐸], [$serif(e)$], [𝑒],
      [$serif(F)$], [𝐹], [$serif(f)$], [𝑓],
      [$serif(G)$], [𝐺], [$serif(g)$], [𝑔],
      [$serif(H)$], [𝐻], [$serif(h)$], [ℎ],
      [$serif(I)$], [𝐼], [$serif(i)$], [𝑖],
      [$serif(J)$], [𝐽], [$serif(j)$], [𝑗],
      [$serif(K)$], [𝐾], [$serif(k)$], [𝑘],
      [$serif(L)$], [𝐿], [$serif(l)$], [𝑙],
      [$serif(M)$], [𝑀], [$serif(m)$], [𝑚],
      [$serif(N)$], [𝑁], [$serif(n)$], [𝑛],
      [$serif(O)$], [𝑂], [$serif(o)$], [𝑜],
      [$serif(P)$], [𝑃], [$serif(p)$], [𝑝],
      [$serif(Q)$], [𝑄], [$serif(q)$], [𝑞],
      [$serif(R)$], [𝑅], [$serif(r)$], [𝑟],
      [$serif(S)$], [𝑆], [$serif(s)$], [𝑠],
      [$serif(T)$], [𝑇], [$serif(t)$], [𝑡],
      [$serif(U)$], [𝑈], [$serif(u)$], [𝑢],
      [$serif(V)$], [𝑉], [$serif(v)$], [𝑣],
      [$serif(W)$], [𝑊], [$serif(w)$], [𝑤],
      [$serif(X)$], [𝑋], [$serif(x)$], [𝑥],
      [$serif(Y)$], [𝑌], [$serif(y)$], [𝑦],
      [$serif(Z)$], [𝑍], [$serif(z)$], [𝑧],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*], [*Symbol*],
      [$serif(Alpha)$], [$ Α $], [$serif(alpha)$], [$ 𝛼 $],
      [$serif(Beta)$], [$ Β $], [$serif(beta)$], [$ 𝛽 $],
      [$serif(Gamma)$], [$ Γ $], [$serif(gamma)$], [$ 𝛾 $],
      [$serif(Delta)$], [$ Δ $], [$serif(delta)$], [$ 𝛿 $],
      [$serif(Digamma)$], [$ Ϝ $], [$serif(digamma)$], [$ ϝ $],
      [$serif(Epsilon)$], [$ Ε $], [$serif(epsilon)$], [$ 𝜀 $],
      [$serif(Zeta)$], [$ Ζ $], [$serif(zeta)$], [$ 𝜁 $],
      [$serif(Eta)$], [$ Η $], [$serif(eta)$], [$ 𝜂 $],
      [$serif(Theta)$], [$ Θ $], [$serif(theta)$], [$ 𝜃 $],
      [$serif(Iota)$], [$ Ι $], [$serif(iota)$], [$ 𝜄 $],
      [$serif(Kappa)$], [$ Κ $], [$serif(kappa)$], [$ 𝜅 $],
      [$serif(Lambda)$], [$ Λ $], [$serif(lambda)$], [$ 𝜆 $],
      [$serif(Mu)$], [$ Μ $], [$serif(mu)$], [$ 𝜇 $],
      [$serif(Nu)$], [$ Ν $], [$serif(nu)$], [$ 𝜈 $],
      [$serif(Xi)$], [$ Ξ $], [$serif(xi)$], [$ 𝜉 $],
      [$serif(Omicron)$], [$ Ο $], [$serif(omicron)$], [$ 𝜊 $],
      [$serif(Pi)$], [$ Π $], [$serif(pi)$], [$ 𝜋 $],
      [$serif(Rho)$], [$ Ρ $], [$serif(rho)$], [$ 𝜌 $],
      [$serif(Sigma)$], [$ Σ $], [$serif(sigma)$], [$ 𝜎 $],
      [$serif(Tau)$], [$ Τ $], [$serif(tau)$], [$ 𝜏 $],
      [$serif(Upsilon)$], [$ Υ $], [$serif(upsilon)$], [$ 𝜐 $],
      [$serif(Phi)$], [$ Φ $], [$serif(phi)$], [$ 𝜑 $],
      [$serif(Chi)$], [$ Χ $], [$serif(chi)$], [$ 𝜒 $],
      [$serif(Psi)$], [$ Ψ $], [$serif(psi)$], [$ 𝜓 $],
      [$serif(Omega)$], [$ Ω $], [$serif(omega)$], [$ 𝜔 $],
      [], [], [$serif(epsilon.alt)$], [$ 𝜖 $],
      [], [], [$serif(Theta.alt)$], [$ ϴ $],
      [], [], [$serif(theta.alt)$], [$ 𝜗 $],
      [], [], [$serif(kappa.alt)$], [$ 𝜘 $],
      [], [], [$serif(pi.alt)$], [$ 𝜛 $],
      [], [], [$serif(rho.alt)$], [$ 𝜚 $],
      [], [], [$serif(sigma.alt)$], [$ 𝜍 $],
      [], [], [$serif(phi.alt)$], [$ 𝜙 $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$serif(0)$], [0],
      [$serif(1)$], [1],
      [$serif(2)$], [2],
      [$serif(3)$], [3],
      [$serif(4)$], [4],
      [$serif(5)$], [5],
      [$serif(6)$], [6],
      [$serif(7)$], [7],
      [$serif(8)$], [8],
      [$serif(9)$], [9],
    )
  ],
)

#pagebreak()

= Upright (upright)

#grid(
  columns: (1fr, 1fr, 0.5fr),
  gutter: 0.5cm,
  align: center,
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Latin Upper*], [*Symbol*], [*Latin Lower*], [*Symbol*],
      [$upright(A)$], [A], [$upright(a)$], [a],
      [$upright(B)$], [B], [$upright(b)$], [b],
      [$upright(C)$], [C], [$upright(c)$], [c],
      [$upright(D)$], [D], [$upright(d)$], [d],
      [$upright(E)$], [E], [$upright(e)$], [e],
      [$upright(F)$], [F], [$upright(f)$], [f],
      [$upright(G)$], [G], [$upright(g)$], [g],
      [$upright(H)$], [H], [$upright(h)$], [h],
      [$upright(I)$], [I], [$upright(i)$], [i],
      [$upright(J)$], [J], [$upright(j)$], [j],
      [$upright(K)$], [K], [$upright(k)$], [k],
      [$upright(L)$], [L], [$upright(l)$], [l],
      [$upright(M)$], [M], [$upright(m)$], [m],
      [$upright(N)$], [N], [$upright(n)$], [n],
      [$upright(O)$], [O], [$upright(o)$], [o],
      [$upright(P)$], [P], [$upright(p)$], [p],
      [$upright(Q)$], [Q], [$upright(q)$], [q],
      [$upright(R)$], [R], [$upright(r)$], [r],
      [$upright(S)$], [S], [$upright(s)$], [s],
      [$upright(T)$], [T], [$upright(t)$], [t],
      [$upright(U)$], [U], [$upright(u)$], [u],
      [$upright(V)$], [V], [$upright(v)$], [v],
      [$upright(W)$], [W], [$upright(w)$], [w],
      [$upright(X)$], [X], [$upright(x)$], [x],
      [$upright(Y)$], [Y], [$upright(y)$], [y],
      [$upright(Z)$], [Z], [$upright(z)$], [z],
    )
  ],
  [
    #table(
      columns: 4,
      align: center,
      stroke: 0.5pt,
      [*Greek Upper*], [*Symbol*], [*Greek Lower*], [*Symbol*],
      [$upright(Alpha)$], [$ Α $], [$upright(alpha)$], [$ α $],
      [$upright(Beta)$], [$ Β $], [$upright(beta)$], [$ β $],
      [$upright(Gamma)$], [$ Γ $], [$upright(gamma)$], [$ γ $],
      [$upright(Delta)$], [$ Δ $], [$upright(delta)$], [$ δ $],
      [$upright(Digamma)$], [$ Ϝ $], [$upright(digamma)$], [$ ϝ $],
      [$upright(Epsilon)$], [$ Ε $], [$upright(epsilon)$], [$ ε $],
      [$upright(Zeta)$], [$ Ζ $], [$upright(zeta)$], [$ ζ $],
      [$upright(Eta)$], [$ Η $], [$upright(eta)$], [$ η $],
      [$upright(Theta)$], [$ Θ $], [$upright(theta)$], [$ θ $],
      [$upright(Iota)$], [$ Ι $], [$upright(iota)$], [$ ι $],
      [$upright(Kappa)$], [$ Κ $], [$upright(kappa)$], [$ κ $],
      [$upright(Lambda)$], [$ Λ $], [$upright(lambda)$], [$ λ $],
      [$upright(Mu)$], [$ Μ $], [$upright(mu)$], [$ μ $],
      [$upright(Nu)$], [$ Ν $], [$upright(nu)$], [$ ν $],
      [$upright(Xi)$], [$ Ξ $], [$upright(xi)$], [$ ξ $],
      [$upright(Omicron)$], [$ Ο $], [$upright(omicron)$], [$ ο $],
      [$upright(Pi)$], [$ Π $], [$upright(pi)$], [$ π $],
      [$upright(Rho)$], [$ Ρ $], [$upright(rho)$], [$ ρ $],
      [$upright(Sigma)$], [$ Σ $], [$upright(sigma)$], [$ σ $],
      [$upright(Tau)$], [$ Τ $], [$upright(tau)$], [$ τ $],
      [$upright(Upsilon)$], [$ Υ $], [$upright(upsilon)$], [$ υ $],
      [$upright(Phi)$], [$ Φ $], [$upright(phi)$], [$ φ $],
      [$upright(Chi)$], [$ Χ $], [$upright(chi)$], [$ χ $],
      [$upright(Psi)$], [$ Ψ $], [$upright(psi)$], [$ ψ $],
      [$upright(Omega)$], [$ Ω $], [$upright(omega)$], [$ ω $],
      [], [], [$upright(epsilon.alt)$], [$ ϵ $],
      [], [], [$upright(Theta.alt)$], [$ ϴ $],
      [], [], [$upright(theta.alt)$], [$ ϑ $],
      [], [], [$upright(kappa.alt)$], [$ ϰ $],
      [], [], [$upright(pi.alt)$], [$ ϖ $],
      [], [], [$upright(rho.alt)$], [$ ϱ $],
      [], [], [$upright(sigma.alt)$], [$ ς $],
      [], [], [$upright(phi.alt)$], [$ ϕ $],
    )
  ],
  [
    #table(
      columns: 2,
      align: center,
      stroke: 0.5pt,
      [*Number*], [*Symbol*],
      [$upright(0)$], [0],
      [$upright(1)$], [1],
      [$upright(2)$], [2],
      [$upright(3)$], [3],
      [$upright(4)$], [4],
      [$upright(5)$], [5],
      [$upright(6)$], [6],
      [$upright(7)$], [7],
      [$upright(8)$], [8],
      [$upright(9)$], [9],
    )
  ],
)

#pagebreak()
